DO BEGIN

	
	--CREACIÓN DE TABLAS DE BKP PARA PRUEBAS
	IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= 'EXT' and TABLE_NAME = 'CARTERA_BKP_20251103_PRD') IS NULL THEN
        CREATE COLUMN TABLE EXT.CARTERA_BKP_20251103_PRD AS (SELECT * FROM EXT.CARTERA);
	END IF;
	
	TRUNCATE TABLE EXT.CARTERA;
	INSERT INTO EXT.CARTERA SELECT * FROM EXT.CARTERA_BKP_20251103_PRD;
	
	--ELIMINO EXPEDIENTES MANUALES
	DELETE FROM EXT.CARTERA WHERE MODIF_USER = 'MANUAL-EXPEDIENTE' AND NUM_FIANZA IS NULL;
	
	--CREACIÓN DE EXPEDIENTES
	INSERT INTO EXT.CARTERA(RAMO
		, NUM_POLIZA
		, IDPRODUCT
		, IDMODALIDAD
		, NUM_ANUALIDAD
		, FECHA_INICIO
		, FECHA_FIN
		, IDPAIS
		, MODIF_USER
    	, P_INTERMEDIACION
    	, COD_MEDIADOR
    	, COD_SUBCLAVE
    	, NUM_EXPEDIENTE
		, CREATEDATE
		, ACTIVO
    	)
	SELECT 'CAUCION'
		, NUM_POLIZA
    	, '' IDPRODUCT
		, MOD
    	, 0 NUM_ANUALIDAD
		, COALESCE(FEC_INI,'1990-12-31')
	    , CASE WHEN FEC_FIN = '0000-00-00' THEN '2200-01-01'
	    	ELSE COALESCE(FEC_FIN,'2200-01-01')
	    	END FECHA_FIN
		, CASE WHEN PAIS = 'ESP' THEN 116
			WHEN PAIS = 'PRT' THEN 112 
			END IDPAIS
        , 'EXPEDIENTE-RELASUJE'
        , INTERMEDIA
        , SUBSTRING(POSITIONNAME,1,4) COD_MEDIADOR
        , RIGHT(POSITIONNAME,4) COD_SUBCLAVE
		, NUM_POLIZA
		, CURRENT_TIMESTAMP
		, 1 --ACTIVO
	FROM EXT.RELASUJE R
	WHERE LPAD(MOD,3,0) IN ('091','098')
	AND NOT EXISTS (SELECT 1 FROM EXT.CARTERA C WHERE C.RAMO = 'CAUCION' AND C.NUM_FIANZA IS NULL AND C.MODIF_USER NOT LIKE '%EXPEDIENTE%' AND C.NUM_POLIZA = R.NUM_POLIZA)
	;
	
	--ELIMINAMOS DUPLICADOS
	
	TEMP_CREDITO = SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE,COUNT(*)
			FROM EXT.CARTERA
			WHERE RAMO = 'CREDITO'
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
	
	SELECT 'INICIO-CREDITO',*
	FROM EXT.CARTERA
		WHERE (NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CREDITO)
			AND ACTIVO = 1
		ORDER BY NUM_POLIZA,NUM_ANUALIDAD; 
	
	
	TEMP_CAUCION = SELECT NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,COUNT(*)
				FROM EXT.CARTERA
				WHERE RAMO = 'CAUCION'
				AND ACTIVO = 1
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				HAVING COUNT(*) > 1
				ORDER BY NUM_POLIZA,NUM_FIANZA;
	
	SELECT 'INICIO-CAUCION',*
	FROM EXT.CARTERA
	WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CAUCION)
		AND ACTIVO = 1
		AND NUM_FIANZA IS NOT NULL
	ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
	
	--PROCEDIMIENTO ELIMINAR DUPLICADOS
	CALL EXT.SP_CORREGIR_POLIZAS_DUPLICADAS_PRD();
	
	--DESACTIVAMOS PÓLIZAS QUE NO EXISTAN EN RELASUJE
	UPDATE C
	SET C.ACTIVO = 0,
		MODIF_USER = 'MANUAL - NO EXISTE RELASUJE',
		MODIF_DATE = CURRENT_TIMESTAMP
	FROM EXT.CARTERA C 
	LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0)
	WHERE R.NUM_POLIZA IS NULL
		AND C.ACTIVO > 0;

	--FINAL	
	SELECT 'FINAL-CREDITO',*
	FROM EXT.CARTERA
		WHERE (NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE 
																					FROM :TEMP_CREDITO)
			AND ACTIVO = 1
		ORDER BY NUM_POLIZA,NUM_ANUALIDAD; 
	
	SELECT 'FINAL-CAUCION',*
	FROM EXT.CARTERA
	WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE 
																				FROM :TEMP_CAUCION)
		AND ACTIVO = 1
		AND NUM_FIANZA IS NOT NULL
	ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
	
	SELECT * FROM EXT.CARTERA
	WHERE MODIF_USER = 'MANUAL - NO EXISTE RELASUJE'
	ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_ANUALIDAD;
	
END;