--BACKUP DE TABLA CARTERA
CREATE COLUMN TABLE EXT.CARTERA_BKP_20240911 as
(select * FROM EXT.CARTERA)

-- RESTAURAR CARTERA
DRP TABLE EXT.CARTERA
CREATE COLUMN TABLE EXT.CARTERA as
(select * FROM EXT.CARTERA_BKP_20231214)

select distinct MODIF_SOURCE from EXT.CARTERA_BKP_20231214


-- DATOS DE CARTERA CREDITO PARA REPETICION DE CARGA
-- BORRADO tablas de carga:
DELETE from EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST;
DELETE FROM EXT.CARTERA WHERE RAMO='CREDITO';

-- DATOS DE CARTERA CAUCION PARA REPETICION DE CARGA
-- BORRADO tablas de carga:
DELETE from EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST;
DELETE FROM EXT.CARTERA WHERE RAMO='CAUCION';

-- PROCESAR FICHEROS MVCAR y MVFID de carga inicial

-- Borrar registros modificados manualmente el 6NOV
DELETE from EXT.CARTERA where NUM_POLIZA in (select NUM_POLIZA from EXT.CARTERA_POLIZAS6NOV) and RAMO='CREDITO'

-- Insertar los registros modificados
INSERT INTO EXT.CARTERA 
select * from EXT.CARTERA_POLIZAS6NOV
--- COPIAR PLAN DE COMISIONAMIENTO DE UNA SUBCLAVE EN OTRA
INSERT INTO EXT.PLAN_COMISIONAMIENTO
select distinct 
'1109-1008' as POSITIONNAME, IDPRODUCT, PRODUCTNAME, EFFECTIVESTARTDATE, EFFECTIVEENDDATE, P_EMISION, P_RENOVACION,
current_timestamp as CREATEDATE, current_timestamp as MODIF_DATE, 'NewPortalAdmin' as MODIF_USER, 'COPIA' as MODIF_SOURCE, RAMO
 from EXT.PLAN_COMISIONAMIENTO where POSITIONNAME='1109-0008'
 
 
-- ACTUALIZAR LOS PORCENTAJES ESPECIALES - Nos los pasaron hace un tiempo y cargamos los valores en una Temporal. Con esta query se actualizan en cartera:
UPDATE EXT.cartera CA
set CA.P_ESPECIAL_EMISION = OP.P_EMISION, CA.P_ESPECIAL_RENOVACION = OP.P_RENOVACION,
CA.FECHA_FIN = CASE WHEN OP.FEC_FIN = '' then CA.FECHA_FIN else OP.FEC_FIN end, 
MODIF_USER='OP_ESP', MODIF_DATE = current_timestamp
from EXT.cartera CA
INNER JOIN EXT.TMP_COMISIONES_ESP as OP
ON CA.IDMODALIDAD = OP.MODALIDAD and CA.NUM_POLIZA=OP.NUM_POLIZA  and CA.COD_MEDIADOR=OP.COD_MEDIADOR and CA.COD_SUBCLAVE=OP.COD_SUBCLAVE

-- INSERTAR EN PLAN COMISIONAMIENTO
INSERT INTO EXT.PLAN_COMISIONAMIENTO VALUES('1734-0000','511PT','Poliza Facil','2023-06-01','2200-01-01',0.1000 ,0.1000 ,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP,'INICIAL','actualizacion 29dic23 cuadro comisiones SAP.xlsx','CREDITO');

-- Actualizar poliza a activa
UPDATE EXT.CARTERA set ACTIVO=1, FECHA_INICIO = '2023-09-23' , MODIF_USER='NewPortalAdmin', MODIF_DATE = current_timestamp where NUM_POLIZA = 1002187 and NUM_ANUALIDAD=3

-- cOMPROBACIÓN DE LA ACTUALIZACIÓN:
select CA.IDMODALIDAD, CA.NUM_POLIZA, CA.COD_MEDIADOR, CA.COD_SUBCLAVE, CA.FECHA_VENCIMIENTO, 
cA.FECHA_INICIO, CA.FECHA_FIN,OP.FEC_INI, OP.FEC_FIN , CASE WHEN OP.FEC_FIN = '' then CA.FECHA_FIN else OP.FEC_FIN end NEW_FIN , 
CA.P_ESPECIAL_EMISION, CA.P_ESPECIAL_RENOVACION,OP.P_EMISION, OP.P_RENOVACION, MODIF_SOURCE, MODIF_DATE
from EXT.cartera CA
INNER JOIN EXT.TMP_COMISIONES_ESP as OP
ON CA.IDMODALIDAD = OP.MODALIDAD and CA.NUM_POLIZA=OP.NUM_POLIZA  and CA.COD_MEDIADOR=OP.COD_MEDIADOR and CA.COD_SUBCLAVE=OP.COD_SUBCLAVE

-- COmprobaciones:
-- POLIZAS DE CREDITO CON FECHA INICIO Mayor que fecha vencimiento (corresponde a una mediación futura)
select NUM_POLIZA, FECHA_EFECTO, FECHA_VENCIMIENTO, FECHA_INICIO, FECHA_FIN, COD_MEDIADOR, COD_SUBCLAVE, P_INTERMEDIACION from EXT.CARTERA where FECHA_INICIO > FECHA_VENCIMIENTO and RAMO='CREDITO'
-- Movimientos CARTERA
Select IDMODALIDAD, NUM_POLIZA, NUM_ANUALIDAD, ID_SIT_ANUALIDAD, DESC_SIT_ANUALIDAD, FECHA_SIT_ANUALIDAD, 
FECHA_EMISION, FECHA_EFECTO, FECHA_VENCIMIENTO, IDMEDIADOR, NOMBRE_MEDIADOR, FECHA_INI, FECHA_FIN, 
DESC_SUBCLAVE, IDSUBCLAVE, PORC_INTERMEDIACION, IDTIPO_MOV, BATCHNAME, CREATEDATE, ESTADOREG 
from EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST where NUM_POLIZA=1002187


--///////////////////////////////////////////////////////////////////////
-- MOVIMIENTOS RECIBO
--///////////////////////////////////////////////////////////////////////
-- Si es necesario (por recarga completa, borrar todos los historicos y tablas de STAGE (en producción hay que hacerlo con Touchless Deployment para las tablas de TCMP)
--liquibase formatted sql
--changeset mrodellar:1 
-- Tablas de RECIBOS
DELETE from CS_STAGESALESORDER where BATCHNAME like '%MVREC%202311%'
DELETE from CS_STAGESALESTRANSACTION where BATCHNAME like '%MVREC%';
DELETE from CS_STAGETRANSACTIONASSIGN where BATCHNAME like '%MVREC%';
DELETE from EXT.EXT_TXN_RECIBOS where BATCHNAME like '%MVREC%';
DELETE from EXT.EXT_TXNASIG_RECIBOS where BATCHNAME like '%MVREC%';
DELETE from EXT.EXT_MOVIMIENTO_RECIBOS_HIST where BATCHNAME like '%MVREC%';
DELETE FROM EXT.EXT_MOVIMIENTO_RECIBOS_NO_VALIDADAS where BATCHNAME like '%MVREC%';

--VALIDAR PROCESO EN LOG
select * from EXT.CSE_DEBUG where DATETIME> '2023-10-19 10:45'

select * from EXT.CSE_DEBUG where DATETIME> '2023-12-04 16:23'

-- COMPROBAR REGISTROS CARTERA
select ACTIVO, IDPAIS, IDPRODUCT, NUM_POLIZA, NUM_FIANZA, NUM_ANUALIDAD, FECHA_EFECTO, FECHA_VENCIMIENTO, 
COD_MEDIADOR, COD_SUBCLAVE, P_INTERMEDIACION, FECHA_INICIO, FECHA_FIN, P_ESPECIAL_EMISION, P_ESPECIAL_RENOVACION, NOMBRE_TOMADOR, MODIF_SOURCE 
from EXT.CARTERA where NUM_POLIZA = 1008553 and NUM_FIANZA=45272

-- CARGA DE RECIBOS DE CARTERA (CREDITO)
Select CREATEDATE, IDTIPO_MOV, IDMODALIDAD, NUM_POLIZA, NUM_ANUALIDAD as ANUALIDAD, ID_SIT_ANUALIDAD || ' ' || DESC_SIT_ANUALIDAD as SITUACION, FECHA_SIT_ANUALIDAD as FEC_SIT, 
FECHA_EMISION, FECHA_EFECTO as FEC_EFECTO, FECHA_VENCIMIENTO  as FEC_VCTO, IDMEDIADOR, NOMBRE_MEDIADOR, FECHA_INI, FECHA_FIN, 
DESC_SUBCLAVE, IDSUBCLAVE, PORC_INTERMEDIACION as P_INT,  BATCHNAME, ESTADOREG 
from EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST where NUM_POLIZA=09129460 and NUM_ANUALIDAD=7


Select FECHA_DATOS, COD_OPERACION, COD_AVAL, NUM_RECIBO, TIPO_MVTO,DESC_MVTO, NUM_MVTO, TIPO_RECIBO, DESC_TIPO_RECIBO, IMPORTE_TOTAL_RECIBO, IMPORTE_MVTO_RIESGO from EXT.EXT_MOVIMIENTO_RECIBOS_HIST where COD_OPERACION like '%1003114%' and COD_AVAL in (1003114180006)

Select FECHA_DATOS, COD_OPERACION, NUM_RECIBO, NUM_MVTO, DESC_MVTO, FECHA_EFECTO_ANUALIDAD, IMPORTE_TOTAL_RECIBO, DESC_SITUACION_RECIBO, NOMBRE_EMPRESA, COD_RIESGO, IMPORTE_MVTO_RIESGO 
 FROM  EXT.EXT_MOVIMIENTO_RECIBOS_HIST where COD_OPERACION like '%34109114033000000000%'
 
Select * from EXT.EXT_MOVIMIENTO_RECIBOS_HIST where COD_OPERACION like '%9156467%' and NUM_RECIBO ='13'
select * from EXT.PLAN_COMISIONAMIENTO where POSITIONNAME ='0648-0000' and RAMO='CAUCION' and IDPRODUCT='091C001'
-- VERIFICACION DEL QUERY FOR VALUE APLICADO
SELECT * FROM ( SELECT * from EXT.PLAN_COMISIONAMIENTO where IDPRODUCT = '511SP' and POSITIONNAME = '1109-0008' and EFFECTIVESTARTDATE <= '2023-10-12' and EFFECTIVEENDDATE > '2023-10-12' UNION SELECT * from EXT.PLAN_COMISIONAMIENTO where IDPRODUCT = substring('511SP',1,3)  and POSITIONNAME = '1109-0008' and EFFECTIVESTARTDATE <= '2023-10-12' and EFFECTIVEENDDATE > '2023-10-12' )


------------------------------------
--CONTABILIDAD
------------------------------------
-- ANTES DE REPROCESAR CONTABILIDAD (VALORAR SI HAY QUE BORRAR DATOS DE CONTABILIDAD YA ENVIADOS)
DELETE FROM EXT.RETORNO_CONTABILIDAD where FECHADATOS = '2023-08-01'
o por Periodo
DELETE from EXT.RETORNO_CONTABILIDAD where PERIODSEQ=2533274790397190  -- borrar Noviembre

EJECUTAR PIPELINE DataExtract para el periodo que se quiere extraer, con el tipo de fichero: CONTADATEXT
------------------------------------
-- ACTUALIZAR P_INTERMEDIACION para una poliza
UPDATE EXT.CARTERA  set P_INTERMEDIACION=100.00 where NUM_POLIZA = 7516686 
UPDATE EXT.CARTERA set P_INTERMEDIACION = 100.00, MODIF_USER ='MANUAL' where MODIF_SOURCE like '%202311%INI%' and P_INTERMEDIACION = 0 
------------------------------------
--RESULTADOS
------------------------------------
-- Pestaña 1 - Extraer registros sin datos en CARTERA
SELECT 
CASE WHEN SUBSTRING(COD_OPERACION, 1, 3) <> '091' and SUBSTRING(COD_OPERACION, 1, 3) <> '098'
THEN CASE WHEN (select count(*) from EXT.CARTERA where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_ANUALIDAD = NUM_PERIODO ) > 0 
     Then CASE WHEN (select to_varchar(max(FECHA_EFECTO)) from EXT.CARTERA 
                  where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_ANUALIDAD = NUM_PERIODO ) <> FECHA_EFECTO_ANUALIDAD
          Then  'Fecha Efecto no coincide: ' || (select to_varchar(max(FECHA_EFECTO)) from EXT.CARTERA 
                  where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_ANUALIDAD = NUM_PERIODO )
          Else CASE WHEN  (select min(ACTIVO) from EXT.CARTERA where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_ANUALIDAD = NUM_PERIODO ) = 0
              Then 'Poliza anulada para anualidad ' || to_varchar(NUM_PERIODO )
              else CASE WHEN (select max(IDPAIS) from EXT.CARTERA where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_ANUALIDAD = NUM_PERIODO ) <> IDPAIS
                    Then 'Pais Poliza no coincide con pais de Recibo ' || to_varchar(IDPAIS )
                    else 'Pte. Revisión manual'
                   end
              end
          end
     Else 'No hay polizas para esa anualidad' 
 END
ELSE  CASE WHEN (select count(*) from EXT.CARTERA where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_FIANZA = COD_AVAL ) > 0 
       Then CASE WHEN (select to_varchar(max(FECHA_EFECTO)) from EXT.CARTERA 
                  where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_FIANZA = COD_AVAL ) <> FECHA_EFECTO_ANUALIDAD
            Then 'Fecha Efecto no coincide: ' || (select to_varchar(max(FECHA_EFECTO)) from EXT.CARTERA 
                  where NUM_POLIZA = SUBSTRING(COD_OPERACION, 4, 8) and NUM_FIANZA = COD_AVAL )
            Else  'Pte. Revisión manual'
             End
        Else 'No hay poliza/aval'
  END
END as MOTIVO,
IDCOMPANIA as CIA,
IDPAIS as SUCURSAL,
IDDIVISA AS DIVISA,
'' as TIPO_AGENTE,
'' as MEDIADOR,
'' as NOMBRE_MEDIADOR,
'' as SUBMEDIADOR ,
'' as NOMBRE_SUBMEDIADOR ,
SUBSTRING(COD_OPERACION, 1, 3) as MODALIDAD,
SUBSTRING(COD_OPERACION, 4, 8) as NUM_POLIZA,
NUM_RECIBO as NUM_RECIBO,
NUM_PERIODO as ANUALIDAD,
'' as NUM_AVAL,
COD_AVAL as NUM_FIANZA,
REPLACE(NOMBRE_EMPRESA, ',', ';') as TOMADOR,
FECHA_EFECTO_ANUALIDAD as FEC_EFECANUA,
FECHA_EMISION as FEC_EMISREC,
FECHA_COBRO as FEC_COBRO,
DESC_TIPO_RECIBO as TPO_PRIMA,
COD_RIESGO as COD_RIESGO,
'' as AMBITO,
IMPORTE_MVTO_RIESGO as IMP_TOTAL,
'' as POR_COMISION,
'' as IMP_COMISION,
'' AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
'' as Estado_Recibo,
FECHA_DATOS,
BATCHNAME as FICHERO_CARGA, ID
--from EXT."EXT_MOVIMIENTO_RECIBOS_HIST" where ESTADOREG = 'NO_CARTERA'  
from EXT."EXT_MOVIMIENTO_RECIBOS_HIST" where ESTADOREG = 'NO_CARTERA'  
and TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD') <= '2024-09-30' and TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD') >= '2024-09-01'
 
-- PESTAÑA 2 EXTRAER DATOS QUE EXISNTE EN CARTERA PARA CANAL DIRECTO - MEDIADOR=0000
Select 
TX.GENERICATTRIBUTE11 as CIA,
TX.GENERICATTRIBUTE12 as SUCURSAL,
TX.GENERICATTRIBUTE16 AS DIVISA,
'' as TIPO_AGENTE,
'0000' as MEDIADOR,
'' as NOMBRE_MEDIADOR,
'0000' as SUBMEDIADOR ,
'' as NOMBRE_SUBMEDIADOR ,
SUBSTRING(TX.ORDERID, 1, 3) as MODALIDAD,
TX.GENERICATTRIBUTE1 as NUM_POLIZA,
TX.GENERICATTRIBUTE2 as NUM_RECIBO,
Cast(TX.GENERICNUMBER3 as integer)  as ANUALIDAD,
'' as NUM_AVAL,
TX.GENERICATTRIBUTE5 as NUM_FIANZA,
REPLACE(TX.GENERICATTRIBUTE15, ',', ';')  as TOMADOR,
TO_NVARCHAR(TX.GENERICDATE5,'YYYY-MM-DD') as FEC_EFECANUA,
TO_NVARCHAR(TX.GENERICDATE1,'YYYY-MM-DD') as FEC_EMISREC,
TO_NVARCHAR(TX.GENERICDATE2,'YYYY-MM-DD') as FEC_COBRO,
TX.GENERICATTRIBUTE18 as TPO_PRIMA,
TX.GENERICATTRIBUTE20 as COD_RIESGO,
TX.GENERICATTRIBUTE21 as AMBITO,
REPLACE(CAST(ROUND(TX.VALUE , 2) AS DECIMAL(10,2)), '.', '.') as IMP_TOTAL,
'' as POR_COMISION,
'' as IMP_COMISION,
'' AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
'' as Estado_Recibo,
TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FECHA_DATOS,
TX.BATCHNAME as FICHERO_CARGA 
from EXT.EXT_TXN_RECIBOS TX where ESTADO='SIN MEDIADOR'  and TO_NVARCHAR(TX.COMPENSATIONDATE, 'YYYY-MM-DD') <= '2024-04-30' and TO_NVARCHAR(TX.COMPENSATIONDATE, 'YYYY-MM-DD') >= '2024-04-01'
and not EXISTS (select 1 from EXT.EXT_TXN_RECIBOS TX2 where TX.ORDERID = TX2.ORDERID and TX.LINENUMBER=TX2.LINENUMBER and TX.SUBLINENUMBER=TX2.SUBLINENUMBER and ESTADO = 'ENVIADA')

--- PESTAÑA 3 -CONSULTA DE RESULTADOS de COMISIONES DE PRIMA
select
TX.GENERICATTRIBUTE11 as CIA,
TX.GENERICATTRIBUTE12 as SUCURSAL,
TX.GENERICATTRIBUTE16 AS DIVISA,
MED.TIPO_MEDIADOR as TIPO_AGENTE,
MED.COD_MEDIADOR as MEDIADOR,
IFNULL(MED.NOMBRE || ' ', '') || MED."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
MED.SUBCLAVE as SUBMEDIADOR ,
MED.NOM_SUBCLAVE as NOMBRE_SUBMEDIADOR ,
SUBSTRING(SO.ORDERID, 1, 3) as MODALIDAD,
TX.GENERICATTRIBUTE1 as NUM_POLIZA,
TX.GENERICATTRIBUTE2 as NUM_RECIBO,
Cast(TX.GENERICNUMBER3 as integer)  as ANUALIDAD,
'' as NUM_AVAL,
TX.GENERICATTRIBUTE5 as NUM_FIANZA,
TX.GENERICATTRIBUTE15 as TOMADOR,
TO_NVARCHAR(TX.GENERICDATE5,'YYYY-MM-DD') as FEC_EFECANUA,
TO_NVARCHAR(TX.GENERICDATE1,'YYYY-MM-DD') as FEC_EMISREC,
TO_NVARCHAR(TX.GENERICDATE2,'YYYY-MM-DD') as FEC_COBRO,
TX.GENERICATTRIBUTE18 as TPO_PRIMA,
TX.GENERICATTRIBUTE20 as COD_RIESGO,
TX.GENERICATTRIBUTE21 as AMBITO,
REPLACE(CAST(ROUND(TX.VALUE , 2) AS DECIMAL(10,2)), '.', ',') as IMP_TOTAL,
REPLACE(CAST(ROUND(CR.GENERICNUMBER1 , 4) AS DECIMAL(10,4)), '.', ',') as POR_COMISION,
REPLACE(CAST(ROUND(CR.GENERICNUMBER3 , 2) AS DECIMAL(10,2)), '.', ',') as IMP_COMISION,
CASE WHEN (cr.NAME like 'CD_%_Comision_Emision%' ) THEN 'EMI' ELSE 'REN' END AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
CR.GENERICATTRIBUTE9 as Estado_Recibo,
TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FECHADATOS,
UT1.NAME as MONEDA_SAP,
CR.GENERICBOOLEAN1 as TRASPASO,
REPLACE(CAST(ROUND( (TA.GENERICNUMBER1 * 100) , 2) AS DECIMAL(10,2)), '.', ',') as P_INTERMEDIACION,
SO.ORDERID, TX.LINENUMBER as LNUM, TX.SUBLINENUMBER, TX.GENERICATTRIBUTE9 as TIPO_MVTO, TX.GENERICATTRIBUTE10 as ID_SITUACION
FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ AND UT1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE PER.NAME in ( 'Septiembre 2024')
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND ( cr.NAME like 'CD_%_Comision_Emision%' or cr.NAME like 'CD_%_Comision_Renovacion%')

-- Comprobación de numero de resultados por día
Select TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FECHADATOS, count(*) as NUM_Resultados
FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ AND UT1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE PER.NAME LIKE 'Agosto 2024'
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND ( cr.NAME like 'CD_%_Comision_Emision%' or cr.NAME like 'CD_%_Comision_Renovacion%')
Group by TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') 

-- Comprobacion de carga por dia
Select TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD') as FECHADATOS, count(*) as NUM_REGISTROS_CARGADOS
from EXT."EXT_MOVIMIENTO_RECIBOS_HIST" where TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD') <= '2024-08-31' 
and TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD') >= '2024-08-01'
Group by TO_NVARCHAR(FECHA_DATOS,'YYYY-MM-DD')

-- PESTAÑA 4 - Transacciones que no han generado creditos
select 
TX.GENERICATTRIBUTE11 as CIA,
TX.GENERICATTRIBUTE12 as SUCURSAL,
TX.GENERICATTRIBUTE16 AS DIVISA,
MED.TIPO_MEDIADOR as TIPO_AGENTE,
TA.GENERICATTRIBUTE2 as MEDIADOR,
IFNULL(MED.NOMBRE || ' ', '') || MED."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
TA.GENERICATTRIBUTE3 as SUBMEDIADOR ,
MED.NOM_SUBCLAVE as NOMBRE_SUBMEDIADOR ,
SUBSTRING(SO.ORDERID, 1, 3) as MODALIDAD,
TX.GENERICATTRIBUTE1 as NUM_POLIZA,
TX.GENERICATTRIBUTE2 as NUM_RECIBO,
Cast(TX.GENERICNUMBER3 as integer)  as ANUALIDAD,
'' as NUM_AVAL,
TX.GENERICATTRIBUTE5 as NUM_FIANZA,
TX.GENERICATTRIBUTE15 as TOMADOR,
TO_NVARCHAR(TX.GENERICDATE5,'YYYY-MM-DD') as FEC_EFECANUA,
TO_NVARCHAR(TX.GENERICDATE1,'YYYY-MM-DD') as FEC_EMISREC,
TO_NVARCHAR(TX.GENERICDATE6,'YYYY-MM-DD') as FEC_COBRO_SITUACION,
TX.GENERICATTRIBUTE18 as TPO_PRIMA,
TX.GENERICATTRIBUTE20 as COD_RIESGO,
TX.GENERICATTRIBUTE21 as AMBITO,
REPLACE(CAST(ROUND(TX.VALUE , 2) AS DECIMAL(10,2)), '.', ',') as IMP_TOTAL,
REPLACE(CAST(ROUND(CR.GENERICNUMBER1 , 4) AS DECIMAL(10,4)), '.', ',') as POR_COMISION,
REPLACE(CAST(ROUND(CR.GENERICNUMBER3 , 2) AS DECIMAL(10,2)), '.', ',') as IMP_COMISION,
'' AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
CR.GENERICATTRIBUTE9 as Estado_Recibo,
ORDERID,
LINENUMBER,
SUBLINENUMBER,
PRODUCTID
from CS_SALESTRANSACTION TX
LEFT JOIN CS_CREDIT CR ON  TX.SALESTRANSACTIONSEQ = CR.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON TX.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON TX.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON  TA.POSITIONNAME = MED.POSITIONNAME
where TO_NVARCHAR(TX.COMPENSATIONDATE, 'YYYY-MM-DD') >= '2024-07-01' and  TO_NVARCHAR(TX.COMPENSATIONDATE, 'YYYY-MM-DD') <= '2024-07-31'
and CR.CREDITSEq is null

-- PESTAÑA 5 - OTROS CONCEPTOS

select 
MED.TIPO_MEDIADOR as TIPO_AGENTE,
MED.COD_MEDIADOR as MEDIADOR,
IFNULL(MED.NOMBRE || ' ', '') || MED."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
MED.SUBCLAVE as SUBMEDIADOR ,
MED.NOM_SUBCLAVE as NOMBRE_SUBMEDIADOR ,
TX.GENERICATTRIBUTE1 as CONCEPTO,
TX.GENERICATTRIBUTE2 as DESCRIPCION,
TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FEC_PAGO,
REPLACE(CAST(ROUND(CR.VALUE , 2) AS DECIMAL(10,2)), '.', ',') as VALOR

FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE PER.NAME LIKE 'Abril 2024'
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND cr.NAME IN ('CD_SP_Subvenciones_Fijas','CD_SP_GastosAgencia','CD_SP_Prestamo_Cuota','CD_SP_Subvenciones_Complementaria') 

-- PESTAÑA LIQUIDACION PROVISIONAL
		SELECT
			TO_NVARCHAR(pay.TRIALPIPELINERUNDATE, 'YYYY-MM-DD') as FECHA_LIQUIDACION,
			med.POSITIONNAME as MEDIADOR,
			(CASE WHEN med.NOMBRE IS NULL THEN '' ELSE med.NOMBRE || ' ' END) || med."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
			CASE WHEN pay.EARNINGCODEID = 'SIN_PAGO' THEN 'SIN_PAGO' ELSE  ec.DESCRIPTION END as CONCEPTO,
			REPLACE(CAST(ROUND(pay.VALUE , 2) AS DECIMAL(10,2)), '.', ',') as IMP_TOTAL,
			ut1.NAME as MONEDA,

			med.NUM_IDENTIFICACION,
			med.TIPO_ID_FISCAL,
			sc.IDSOCIEDAD,
			'000' || CASE WHEN med.BUSINESSUNIT = 'Portugal' then 'V' else fp.VIAPAGO end as COND_PAGO,
			CASE WHEN med.BUSINESSUNIT = 'Portugal' then 'V' else fp.VIAPAGO end as VIAPAGO
		FROM CS_PAYMENT pay 
			INNER JOIN CS_APPLDEPOSITPAYMENTTRACE payapd on pay.PAYMENTSEQ = payapd.PAYMENTSEQ
			INNER JOIN CS_APPLIEDDEPOSIT apd on payapd.APPLIEDDEPOSITSEQ = apd.APPLIEDDEPOSITSEQ
			INNER JOIN CS_DEPOSITAPPLDEPOSITTRACE apddep ON apd.APPLIEDDEPOSITSEQ = apddep.APPLIEDDEPOSITSEQ
			INNER JOIN CS_DEPOSIT dep on apddep.DEPOSITSEQ = dep.DEPOSITSEQ and dep.NAME <> 'D_SP_Ajustes_Manuales'
			LEFT JOIN CS_EARNINGCODE ec on pay.EARNINGCODEID = ec.EARNINGCODEID and ec.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
			LEFT JOIN EXT.MODIFICAR_MEDIADOR med on pay.POSITIONSEQ = med.POSITIONSEQ 
			LEFT JOIN CS_UNITTYPE ut1 on pay.UNITTYPEFORVALUE = ut1.UNITTYPESEQ and ut1.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
			LEFT JOIN EXT.FORMAS_PAGO fp on ( med.FORMA_PAGO || case when med.FACT_PROPIA = 1 then '1' else '0' end ) = fp.IDFORMAPAGO --se tiene en cuenta si es facturacion propia o no
			LEFT JOIN EXT.SOCIEDADES_CESCE sc on sc.IDPAIS = (CASE WHEN dep.GENERICATTRIBUTE1='F' THEN 28 Else med.COD_PAIS END)
		WHERE pay.PERIODSEQ = 2533274790397198

-- CONSULTA INGRESOS POR SERVICIOS:
select
TX.GENERICATTRIBUTE11 as CIA,
TX.GENERICATTRIBUTE12 as SUCURSAL,
TX.GENERICATTRIBUTE16 AS DIVISA,
MED.TIPO_MEDIADOR as TIPO_AGENTE,
MED.COD_MEDIADOR as MEDIADOR,
IFNULL(MED.NOMBRE || ' ', '') || MED."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
MED.SUBCLAVE as SUBMEDIADOR ,
MED.NOM_SUBCLAVE as NOMBRE_SUBMEDIADOR ,
SUBSTRING(SO.ORDERID, 1, 3) as MODALIDAD,
TX.GENERICATTRIBUTE1 as NUM_POLIZA,
TX.GENERICATTRIBUTE2 as NUM_RECIBO,
Cast(TX.GENERICNUMBER3 as integer)  as ANUALIDAD,
'' as NUM_AVAL,
TX.GENERICATTRIBUTE5 as NUM_FIANZA,
TX.GENERICATTRIBUTE15 as TOMADOR,
TO_NVARCHAR(TX.GENERICDATE5,'YYYY-MM-DD') as FEC_EFECANUA,
TO_NVARCHAR(TX.GENERICDATE1,'YYYY-MM-DD') as FEC_EMISREC,
TO_NVARCHAR(TX.GENERICDATE2,'YYYY-MM-DD') as FEC_COBRO,
TX.GENERICATTRIBUTE18 as TPO_PRIMA,
TX.GENERICATTRIBUTE20 as COD_RIESGO,
TX.GENERICATTRIBUTE21 as AMBITO,
REPLACE(CAST(ROUND(TX.VALUE , 2) AS DECIMAL(10,2)), '.', ',') as IMP_TOTAL,
REPLACE(CAST(ROUND(CR.GENERICNUMBER1 , 2) AS DECIMAL(10,2)), '.', ',') as POR_COMISION,
REPLACE(CAST(ROUND(CR.GENERICNUMBER3 , 2) AS DECIMAL(10,2)), '.', ',') as IMP_COMISION,
CASE WHEN (cr.NAME = 'CD_SP_Ingresos_Servicios'  ) THEN 'Ingresos Servicios' ELSE null END AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
CR.GENERICATTRIBUTE9 as Estado_Recibo,
TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FECHADATOS,
UT1.NAME as MONEDA_SAP,
CR.GENERICBOOLEAN1 as TRASPASO
FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE ( PER.NAME LIKE 'Agosto 2023' or PER.NAME LIKE 'Septiembre 2023' )
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND cr.NAME IN ('CD_SP_Ingresos_Servicios')
	


-- RECARGAR OTROS CONCEPTOS
select occ.* from EXT.OTROS_CONCEPTOS_CUOTAS occ where occ.FECHA_PAGO_REAL ='2023/09/30' 
select * from EXT.OTROS_CONCEPTOS_CUOTAS where ESTADO='PENDIENTE' and FECHA_PAGO < '2024/02/01'

UPDATE EXT.OTROS_CONCEPTOS_CUOTAS occ set ESTADO='PTE_PAGO' where occ.FECHA_PAGO_REAL ='2023/09/30' 

-- Borramos de la tabla de CS_STAGE
--Nombre de fichero
select distinct LINENUMBER, BATCHNAME from CS_STAGESALESTRANSACTION where linenumber ='202309'
202309	

--en Touchlessdeployment:
DELETE from CS_STAGESALESTRANSACTION where BATCHNAME like '%OC_20231025_150328.txt%';
DELETE from CS_STAGETRANSACTIONASSIGN where BATCHNAME like '%OC_20231025_150328.txt%';
DELETE from CS_STAGESALESTRANSACTION where BATCHNAME like '%OC_20231106_124337.txt%';
DELETE from CS_STAGETRANSACTIONASSIGN where BATCHNAME like '%OC_20231106_124337.txt%';

---------------------------------------------------------
-- LIQUIDACION
---------------------------------------------------------
-- BORRAR LIQUIDACION PREVIA
--DELETE from EXT.DETALLE_RECIBOS_FACTURAS
--DELETE from EXT.RECIBOS_FACTURAS
--DELETE from EXT.FACTURAS
--DELETE from EXT.DETALLE_FACTURAS
--DELETE from EXT.NUM_FACTURAS
-- RELANZAR LIQUIDACION SIN POST
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299878639, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299878640, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299878998, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299879176, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299879362, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299879579, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299879848, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299880072, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299880370, 'N') -- se pasa el plrunseq
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" (20547673299880793, 'N') -- se pasa el plrunseq

plrunseq 20547673299878561 Julio 2023 PERIODSEQ=2533274790397186
plrunseq 20547673299878639 agosto 2023 PERIODSEQ=2533274790397187
plrunseq 20547673299878640 septiembre 2023 PERIODSEQ=2533274790397188
plrunseq 20547673299878699 - octubre 2023 PERIODSEQ=2533274790397189
plrunseq 20547673299878837 Noviembre 2023 PERIODSEQ=2533274790397190
plrunseq 20547673299878836 Diciembre 2023 PERIODSEQ=2533274790397191
plrunseq 20547673299878998 Enero 2024 PERIODSEQ=2533274790397197
plrunseq 20547673299879176 Febrero 2024 PERIODSEQ=2533274790397198
plrunseq 20547673299879362 Marzo 2024 PERIODSEQ=2533274790397199
plrunseq 20547673299879579 Abril 2024 PERIODSEQ=2533274790397200
plrunseq 20547673299879848 Mayo 2024 PERIODSEQ=2533274790397201
plrunseq 20547673299880072 Junio 2024 PERIODSEQ=2533274790397202
plrunseq 20547673299880370 Julio 2024 PERIODSEQ=2533274790397203
plrunseq 20547673299880793 Agosto 2024 PERIODSEQ=2533274790397204
		
select * from EXT.CSE_DEBUG where DATETIME> '2024-09-03 09:00'
select PIPELINERUNSEQ,PERIODSEQ  from CS_PLRUN where STARTTIME > '2024-07-23 08:00' and DESCRIPTION like '%CompensateAndPay%'
select top 1 PIPELINERUNSEQ,PERIODSEQ  from CS_PLRUN where DESCRIPTION like '%CompensateAndPay%' and PERIODSEQ = (select top 1 PERIODSEQ from CS_PERIOD where NAME='Enero 2024')
----------
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299879362,'1548-0000','N')
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878998,'0347-0000','N')
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878640,'4580-0000','N')
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878561,'1085-0000','N')
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878998,'0079-0000','N')
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878998,'0139-0000','N')

--PROCESO DE LIQUIDACION MANUAL---------------------
Poner Fix Value: FV_PAGA_TODO = 1
LANZAR COMPENSATE & PAY - SPAIN MAYO 2024
LANZAR COMPENSATE & PAY - PORTUGAL MAYO 2024
LANZAR POST  - SPAIN MAYO 2024
LANZAR POST  - PORTUGAL MAYO 2024
EJECUTAR CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST" 
VERIFICAR DETALLES FACTURAS
VERIFICAR IF002
LANZA EXTRACCION CIC
LANZA EXTRACCION GASTOSCIC

---------------------------------------------------------
-- LIQUIDACION PUNTUAL POR MEDIADOR
---------------------------------------------------------
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878560,'1922-0000','N')
UPDATE EXT.RECIBOS_FACTURAS set FECHA_ALTA = '2023-06-30' where IDRECIBO=5757
CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878537,'1922-0000','N')
UPDATE EXT.RECIBOS_FACTURAS set FECHA_ALTA = '2023-07-31' where IDRECIBO=5758
"EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (IN pPlRunSeq BIGINT,IN inPosition NVARCHAR(9), IN actualizaOrder VARCHAR(1)
select PERIODSEQ, NAME from CS_PERIOD PER where ( NAME='Junio 2023' or NAME='Julio 2023' ) AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
plrunseq 20547673299878660 PERIODSEQ:2533274790397185	Junio 2023
plrunseq 20547673299878661 PERIODSEQ:2533274790397186	Julio 2023

select * from CS_PLRUN where PERIODSEQ=2533274790397185

--CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878660,'0124-0000','N')
--CALL "EXT"."SP_GENERAR_RECIBOS_FACTURAS_NOPOST_MEDIADOR" (20547673299878661,'1936-0000','N')

-- BORRADO SELECTIVO DE LIQUIDACION PREVIA
DELETE from EXT.DETALLE_RECIBOS_FACTURAS drf where drf.IDRECIBO in (
select IDRECIBO
from EXT.RECIBOS_FACTURAS rf 
INNER JOIN CS_PERIOD per on rf.PERIODSEQ=per.PERIODSEQ and per.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
and per.NAME='Enero 2024' and rf.CREATEDATE> '2024-02-08 17:00' )

DELETE from EXT.RECIBOS_FACTURAS rf2 where rf2.IDRECIBO in (
select IDRECIBO
from EXT.RECIBOS_FACTURAS rf 
INNER JOIN CS_PERIOD per on rf.PERIODSEQ=per.PERIODSEQ and per.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
and per.NAME='Enero 2024' and rf.CREATEDATE> '2024-02-08 17:00' )

select * from EXT.DETALLE_FACTURAS where IDFACTURA in (
select IDFACTURA
from EXT.FACTURAS f where f.CREATEDATE> '2024-02-08 17:00')

--RECIBOS DE FACTURAS // CONCEPTOS DE LIQUIDACION
select IDRECIBO, per.NAME, CONCEPTO, 
REPLACE(CAST(ROUND(IMPORTE , 2) AS DECIMAL(10,2)), '.', ',') as IMPORTE,
MONEDA, ESTADO, POSITIONNAME as MEDIADOR,
NOMBRE_MEDIADOR as NOMBRE, NUM_IDENTIFICACION, 
Case when BUSINESSUNITNAME = 'Spain' then 'España' else BUSINESSUNITNAME end as PAIS,
SOCIEDAD
from EXT.RECIBOS_FACTURAS rf 
INNER JOIN CS_PERIOD per on rf.PERIODSEQ=per.PERIODSEQ and per.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
and per.NAME='Noviembre 2023'

--DETALLE RECIBOS DE FACTURAS // DETALLE CONCEPTOS DE LIQUIDACION

select
 rf.IDRECIBO,
SOCIEDAD,
 per.NAME, CONCEPTO,
REPLACE(CAST(ROUND(IMPORTE , 2) AS DECIMAL(10,2)), '.', ',') as IMPORTE_TOTAL,
rf.POSITIONNAME as MEDIADOR,
rf.NOMBRE_MEDIADOR as NOMBRE,
Case when BUSINESSUNITNAME = 'Spain' then 'España' else BUSINESSUNITNAME end as PAIS,
IDLINEA,
REPLACE(CAST(ROUND(IMPORTE_DET, 2) AS DECIMAL(10,2)), '.', ',') as IMPORTE_DETALLE,
COD_OPERACION,
NUM_POLIZA,
COD_AVAL,
NUM_RECIBO,
LINENUMBER as RIESGO,
PRODUCTID,
EVENTTYPEID

from EXT.RECIBOS_FACTURAS rf 
INNER JOIN CS_PERIOD per on rf.PERIODSEQ=per.PERIODSEQ and per.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
INNER JOIN EXT.DETALLE_RECIBOS_FACTURAS drf on rf.IDRECIBO=drf.IDRECIBO
and per.NAME='Noviembre 2023' --and rf.IDRECIBO=2458



-- Mediadores en CARTERA QUE NO EXISTEN EN SAP COMMISSIONS
select DISTINCT car.COD_MEDIADOR, car.COD_SUBCLAVE
from  EXT.CARTERA car
left JOIN EXT.MODIFICAR_MEDIADOR med
on car.COD_MEDIADOR = med.COD_MEDIADOR and car.COD_SUBCLAVE = med.SUBCLAVE
where med.COD_MEDIADOR is null and car.COD_MEDIADOR <> '0000'
and FECHA_EFECTO <= CURRENT_DATE and FECHA_VENCIMIENTO > CURRENT_DATE 
order by  car.COD_MEDIADOR, car.COD_SUBCLAVE

--- MEDIADORES QUE SE HAN RECIBIDO EN DATOS HISTORICOS y NO EXISTEN EN SAP COMMISSIONS
select DISTINCT TA.POSITIONNAME
FROM CS_SALESTRANSACTION TX 
	LEFT JOIN CS_TRANSACTIONASSIGNMENT TA  on TX.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ 
	LEFT JOIN EXT.MODIFICAR_MEDIADOR med on TA.POSITIONNAME = med.POSITIONNAME
WHERE med.POSITIONNAME is null

---------------------------------------------------------
-- Comprobación total RECIBOS con suma de detalles
---------------------------------------------------------
select rf.IDRECIBO, rf.CONCEPTO, rf.IMPORTE, sum(drf.IMPORTE_DET) from EXT.RECIBOS_FACTURAS rf
inner join EXT.DETALLE_RECIBOS_FACTURAS drf  on rf.IDRECIBO=drf.IDRECIBO
WHERE rf.IDRECIBO =5148
group by rf.IDRECIBO, rf.CONCEPTO, rf.IMPORTE

-- FACTURAS
select fac.IDFACTURA, fac.CONCEPTO, fac.IMPORTETOTAL, sum(df.IMPORTE_DET) from EXT.FACTURAS fac
inner join EXT.DETALLE_FACTURAS df on fac.IDFACTURA=df.IDFACTURA
WHERE fac.IDFACTURA =2850 
group by fac.IDFACTURA, fac.CONCEPTO, fac.IMPORTETOTAL

---------------------------------------------------------
-- ACTUALIZACION DE LOS CUADROS DE COMISIONES
---------------------------------------------------------

------------------------------------------------------------
--BORRAR REGISTROS SUELTOS YA CARGADOS en MVREC HIST
------------------------------------------------------------
DELETE from EXT.EXT_MOVIMIENTO_RECIBOS_HIST where (COD_OPERACION, COD_AVAL, NUM_RECIBO, NUM_MVTO, COD_GRAVAMEN, COD_RIESGO, TIPO_MVTO) in (
SELECT b.COD_OPERACION, b.COD_AVAL,  b.NUM_RECIBO, b.NUM_MVTO, b.COD_GRAVAMEN, b.COD_RIESGO, b.TIPO_MVTO
		FROM EXT.EXT_MOVIMIENTO_RECIBOS_LOAD b )

--------------------------------------------
-- Polizas traspasadas - Traspaso de polizas de otra original para cargar en clasificación
--------------------------------------------
Select distinct IDPAIS, LPAD(IDMODALIDAD, 3, '0') as IDMODALIDAD, LPAD(NUM_POLIZA, 8, '0') as NUM_POLIZA , NUM_POL_O, FECHA_TRASPASO_POL_O, DESC_SIT_POL_O
from EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST where trim(FECHA_TRASPASO_POL_O) <>'' and DESC_SIT_POL_O in ( 'FINALIZADO' , 'CONFIRMADO' ) 
and (LPAD(IDMODALIDAD, 3, '0') , LPAD(NUM_POLIZA, 8, '0') ) not in (
select distinct clas.NAME as NUEVA_MODALIDAD, clas.CLASSIFIERID as NUEVA_POLIZA
from 
cs_classifier clas,
cs_genericclassifier cgc,
            cs_genericclassifiertype cgct
where clas.classifierseq = cgc.classifierseq
            AND clas.selectorid = cgct.genericclassifiertypeseq
            AND cgct.NAME = 'Forma de Pago' )


------------------------------------------
-- AUDIT
------------------------------------------
select top 100 * from TCMP.CS_AUDITLOG where EVENTDATE > '2023-11-15 12:30' and EVENTTYPE in ('Login', 'Logout') and USERID <> 'NewPortalAdmin'

----------------------
select  month(Fecha_datos) as mes, TIPO_MVTO, DESC_MVTO, count(*) from EXT.EXT_MOVIMIENTO_RECIBOS_HIST group by month(Fecha_datos),TIPO_MVTO, DESC_MVTO

-----------------
CONSULTA DE ESTRUCTURA DE PRIVILEGIOS en Log(workflow)
select 
STRUCTURED_PRIVILEGE_ID,
STRUCTURED_PRIVILEGE_SCHEMA_NAME,
STRUCTURED_PRIVILEGE_NAME,
RESTRICTION_TYPE,
DIMENSION_ATTRIBUTE,
FILTER_ID,
FILTER_TYPE,
NEGATED,
OPERATOR,
OPERAND_ORDER,
to_NVARCHAR(OPERAND) as oper

from STRUCTURED_PRIVILEGES

----------------------------------
-- MVTO COBRADO PREVIO A EIMITIDO
----------------------------------
select * from EXT.EXT_MOVIMIENTO_RECIBOS_HIST WHERE ESTADOREG = 'ENV_ORDER' and TIPO_MVTO='13' and SITUACION_RECIBO='12'

select * from EXT.EXT_MOVIMIENTO_RECIBOS_HIST WHERE COD_OPERACION = '34107516733000000000' and NUM_RECIBO=4 and NUM_MVTO=3
UPDATE  EXT.EXT_MOVIMIENTO_RECIBOS_HIST set ESTADOREG='PTE_EMIS' WHERE COD_OPERACION = '34107516733000000000' and NUM_RECIBO=4 and NUM_MVTO=3

----------------------------------
-- DUPLICADOS CARTERA: ANUALIDAD y MEDIADOR (cambian fechas de efecto)
----------------------------------

select * from EXT.CARTERA where ( IDPRODUCT, NUM_POLIZA, NUM_FIANZA, NUM_ANUALIDAD ) in (
select IDPRODUCT, NUM_POLIZA, NUM_FIANZA, NUM_ANUALIDAD from (
select IDPRODUCT, NUM_POLIZA, NUM_FIANZA, NUM_ANUALIDAD, COD_MEDIADOR, COD_SUBCLAVE, count(*) num_registros 
from EXT.CARTERA group by IDPRODUCT, NUM_POLIZA, NUM_FIANZA, NUM_ANUALIDAD, COD_MEDIADOR, COD_SUBCLAVE having count(*) > 1 ) )

--- MEDIADORES
select POSITIONNAME, BUSINESSUNIT, USERID, MANAGER, IDMANAGER, DIR_TERRITORIAL, TIPO_MEDIADOR from EXT.MODIFICAR_MEDIADOR where Positionname like '%-0%' and BUSINESSUNIT in ('Spain', 'Portugal')

--Detectar polizas que han sido asignadas a su mediador y su subclave
select IDMODALIDAD,NUM_POLIZA, NUM_ANUALIDAD, FECHA_EFECTO, COD_MEDIADOR, COD_SUBCLAVE, FECHA_INICIO, FECHA_FIN, ACTIVO 
from EXT.CARTERA where (IDMODALIDAD,NUM_POLIZA, NUM_ANUALIDAD) in (
select IDMODALIDAD,NUM_POLIZA, NUM_ANUALIDAD from EXT.CARTERA 
where RAMO='CREDITO' and ACTIVO=1
group by IDMODALIDAD,NUM_POLIZA, NUM_ANUALIDAD
having count(distinct COD_MEDIADOR) < count(distinct COD_SUBCLAVE) and count(distinct COD_MEDIADOR)> 0)

----------------------------------
-- POLIZAS que han llegado en mvfid pero no se han cargado por ser de tipo mov. 2 - renovacion y no existir previamente
----------------------------------
select mf.FECHA_DATOS, mf.NUM_POLIZA, mf.NUM_AVAL_FIANZA, CAR.ACTIVO, mf.IDPAIS, mf.IDMODALIDAD,  mf.IDSUBMODALIDAD, mf.NUM_AVAL_HOST, mf.NUM_EXPEDIENTE, mf.FECHA_EFECTO, mf.FECHA_VENCIMIENTO, mf.IDMEDIADOR, mf.IDTIPO_MOV, mf.BATCHNAME, mf.CREATEDATE, mf.ESTADOREG
from EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST mf
LEFT JOIN EXT.CARTERA car on mf.NUM_POLIZA = car.NUM_POLIZA and  mf.NUM_AVAL_FIANZA = car.NUM_FIANZA
where mf.FECHA_DATOS >= '2024-02-01' and mf.IDTIPO_MOV=2 and CAR.ACTIVO is null
---------------------------------------
-- Polizas de cartera con 1 solo mediador y marca MEDIADOR_PRINCIPAL_CIC = 0
---------------------------------------
select * from EXT.CARTERA where (IDMODALIDAD, NUM_POLIZA,NUM_FIANZA, FECHA_EFECTO, NUM_ANUALIDAD) in (
select IDMODALIDAD, NUM_POLIZA,NUM_FIANZA, FECHA_EFECTO, NUM_ANUALIDAD   from EXT.CARTERA where ACTIVO=1
group by IDMODALIDAD, NUM_POLIZA,NUM_FIANZA, FECHA_EFECTO, NUM_ANUALIDAD
having count(*) = 1 ) and MEDIADOR_PRINCIPAL_CIC = 0

-- mediadores sin cuadro comisionamiento de caución
select * from EXT.MODIFICAR_MEDIADOR where POSITIONNAME not in (
Select POSITIONNAME from EXT.PLAN_COMISIONAMIENTO where EFFECTIVESTARTDATE <= current_date AND EFFECTIVEENDDATE >= current_date and ( (RAMO='CAUCION' and IDPRODUCT='091')) ) and COD_PAIS=116 and POSITIONNAME like '%-%' and POSITIONNAME not like '1109%'

---------------------------
-- BACKUPS
---------------------------
-- TABLAS DE FACTURAS
CREATE COLUMN TABLE EXT.RECIBOS_FACTURAS_BKP_20240701 as
(select * FROM EXT.RECIBOS_FACTURAS)

CREATE COLUMN TABLE EXT.DETALLE_RECIBOS_FACTURAS_BKP_20240701 as
(select * FROM EXT.DETALLE_RECIBOS_FACTURAS)

CREATE COLUMN TABLE EXT.DETALLE_FACTURAS_BKP_20240701 as
(select * FROM EXT.DETALLE_FACTURAS)

CREATE COLUMN TABLE EXT.FACTURAS_BKP_20240701 as
(select * FROM EXT.FACTURAS)

CREATE COLUMN TABLE EXT.NUM_FACTURAS_BKP_20240701 as
(select * FROM EXT.NUM_FACTURAS)
-------------------------------------------------------
-- Extraer resultados de un mes a una tabla temporal
-------------------------------------------------------

CREATE COLUMN TABLE EXT.RESULTADOS_202407 as (
select
TX.GENERICATTRIBUTE11 as CIA,
TX.GENERICATTRIBUTE12 as SUCURSAL,
TX.GENERICATTRIBUTE16 AS DIVISA,
MED.TIPO_MEDIADOR as TIPO_AGENTE,
MED.COD_MEDIADOR as MEDIADOR,
IFNULL(MED.NOMBRE || ' ', '') || MED."APELLIDO/RAZON_SOCIAL" as NOMBRE_MEDIADOR,
MED.SUBCLAVE as SUBMEDIADOR ,
MED.NOM_SUBCLAVE as NOMBRE_SUBMEDIADOR ,
SUBSTRING(SO.ORDERID, 1, 3) as MODALIDAD,
TX.GENERICATTRIBUTE1 as NUM_POLIZA,
TX.GENERICATTRIBUTE2 as NUM_RECIBO,
Cast(TX.GENERICNUMBER3 as integer)  as ANUALIDAD,
'' as NUM_AVAL,
TX.GENERICATTRIBUTE5 as NUM_FIANZA,
TX.GENERICATTRIBUTE15 as TOMADOR,
TO_NVARCHAR(TX.GENERICDATE5,'YYYY-MM-DD') as FEC_EFECANUA,
TO_NVARCHAR(TX.GENERICDATE1,'YYYY-MM-DD') as FEC_EMISREC,
TO_NVARCHAR(TX.GENERICDATE2,'YYYY-MM-DD') as FEC_COBRO,
TX.GENERICATTRIBUTE18 as TPO_PRIMA,
TX.GENERICATTRIBUTE20 as COD_RIESGO,
TX.GENERICATTRIBUTE21 as AMBITO,
CAST(ROUND(TX.VALUE , 2) AS DECIMAL(10,2)) as IMP_TOTAL,
CAST(ROUND(CR.GENERICNUMBER1 , 4) AS DECIMAL(10,4)) as POR_COMISION,
CAST(ROUND(CR.GENERICNUMBER3 , 2) AS DECIMAL(10,2)) as IMP_COMISION,
CASE WHEN (cr.NAME like 'CD_%_Comision_Emision%' ) THEN 'EMI' ELSE 'REN' END AS TPO_COMISION,
'' as ESTADO_AGENTE,
'' as FECHA_VENCIMIENTO,
'' as AO_ANUALIDAD,
CR.GENERICATTRIBUTE9 as Estado_Recibo,
TO_NVARCHAR(TX.COMPENSATIONDATE,'YYYY-MM-DD') as FECHADATOS,
UT1.NAME as MONEDA_SAP,
CR.GENERICBOOLEAN1 as TRASPASO,
CAST(ROUND( (TA.GENERICNUMBER1 * 100) , 2) AS DECIMAL(10,2)) as P_INTERMEDIACION,
SO.ORDERID, TX.LINENUMBER as LNUM, TX.SUBLINENUMBER, TX.GENERICATTRIBUTE9 as TIPO_MVTO, TX.GENERICATTRIBUTE10 as ID_SITUACION,
TX.GENERICATTRIBUTE3 as ESTADO_TXN_RECIBO,
CR.CREDITSEQ, MED.POSITIONSEQ, TX.SALESTRANSACTIONSEQ
FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ AND UT1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE PER.NAME in ( 'Julio 2024')
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND ( cr.NAME like 'CD_%_Comision_Emision%' or cr.NAME like 'CD_%_Comision_Renovacion%')

)
-----------------------------------------------------------------------------------
-- GENERAR REGISTRO CARTERA CREDITO A PARTIR DE TABLA HISTORICO ENTRADA
-----------------------------------------------------------------------------------

INSERT INTO EXT.CARTERA 
SELECT
			'CREDITO' as RAMO,
			(SELECT EXT.LIB_GLOBAL_CESCE :getProductId( (select lpad(i.IDMODALIDAD, 3, '0') from dummy), '0', (CASE WHEN (i.IDPAIS > 0 AND i.IDPAIS <= 52) THEN 116 ELSE i.IDPAIS END), i.NUM_POLIZA).productId FROM DUMMY) as IDPRODUCT,
			i.NUM_POLIZA as NUM_POLIZA,
			i.IDMODALIDAD as IDMODALIDAD,
			NULL as IDSUBMODALIDAD,
			0 as NUM_FIANZA,
			NULL as NUM_EXPEDIENTE,
			NULL as NUM_AVAL_HOST,
			i.NUM_ANUALIDAD as NUM_ANUALIDAD,
			i.FECHA_EMISION as FECHA_EMISION,
			i.FECHA_EFECTO as FECHA_EFECTO,
			i.FECHA_VENCIMIENTO FECHA_VENCIMIENTO,
			(CASE WHEN (i.IDPAIS > 0 AND i.IDPAIS <= 52) THEN 116 ELSE i.IDPAIS END) as IDPAIS ,
			i.PRIMA_PROVISIONAL_INT as PRIMA_PROVISIONAL_INT,
			i.PRIMA_PROVISIONAL_EXT as PRIMA_PROVISIONAL_EXT,
			i.IDDIVISA_MERCADO_INT as IDDIVISA_INT,
			i.IDDIVISA_MERCADO_EXT as IDDIVISA_EXT,
			NULL as IDDIVISA_COBERTURA,
			i.PRIMA_MIN_MERCADO_INT as PRIMA_MIN_INT,
			i.PRIMA_MIN_MERCADO_EXT as PRIMA_MIN_EXT,
			lpad(IDMEDIADOR,4,'0') as COD_MEDIADOR,
			lpad(IDSUBCLAVE,4,'0')  as COD_SUBCLAVE,
			( 100 * i.PORC_INTERMEDIACION) as PORC_INTERMEDIACION,
			i.FECHA_EFECTO as FECHA_INI,
			i.FECHA_FIN as FECHA_FIN,
			NULL as P_ESPECIAL_EMISION,
			NULL as P_ESPECIAL_RENOVACION,
			i.IDFISCAL_TOMADOR NIF_TOMADOR,
			'' NOMBRE_TOMADOR, --NOMBRE_TOMADOR  -- NO VIENE EN EL FICHERO
			NULL as FECHA_EFECTO_TRASPASO,
			1 as MEDIADOR_PRINCIPAL_CIC,
			1 AS ACTIVO,
			CURRENT_TIMESTAMP as CREATEDATE,
			CURRENT_TIMESTAMP as MODIF_DATE,
			'MANUAL' as MODIF_USER,
			BATCHNAME as MODIF_SOURCE
			 from EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST i  where NUM_POLIZA=xxxxxx and NUM_ANUALIDAD=xxx 
			 
-----------------------------------------------------------------------------------
-- GENERAR REGISTRO CARTERA CAUCION A PARTIR DE TABLA HISTORICO ENTRADA
-----------------------------------------------------------------------------------
INSERT INTO EXT.CARTERA 
select  'CAUCION' as RAMO,
	(SELECT EXT.LIB_GLOBAL_CESCE:getProductId((select lpad(i.IDMODALIDAD, 3, '0') from dummy) , i.IDSUBMODALIDAD, (CASE WHEN (i.IDPAIS > 0 AND i.IDPAIS <= 52) THEN '116' ELSE i.IDPAIS END), i.NUM_POLIZA).productId FROM DUMMY)  as IDPRODUCT,
	i.NUM_POLIZA  as NUM_POLIZA,
	i.IDMODALIDAD as IDMODALIDAD,
	i.IDSUBMODALIDAD as IDSUBMODALIDAD,
	i.NUM_AVAL_FIANZA as NUM_FIANZA,
	i.NUM_EXPEDIENTE as NUM_EXPEDIENTE,
	i.NUM_AVAL_HOST as NUM_AVAL_HOST,
	0 as NUM_ANUALIDAD,
	i.FECHA_EFECTO as FECHA_EMISION, -- FECHA EMISION
	i.FECHA_EFECTO as FECHA_EFECTO,
	i.FECHA_VENCIMIENTO as FECHA_VENCIMIENTO,
	i.IDPAIS  as IDPAIS,
	NULL as PRIMA_PROVISIONAL_INT,
	NULL as PRIMA_PROVISIONAL_EXT,
	NULL as IDDIVISA_INT,
	NULL as IDDIVISA_EXT,
	i.IDDIVISA_COBERTURA as IDDIVISA_COBERTURA,
	NULL as PRIMA_MIN_INT,
	NULL as PRIMA_MIN_EXT, 
	lpad(SUBSTR_BEFORE(IDMEDIADOR,'-'),4,'0') as COD_MEDIADOR,
	lpad(SUBSTR_AFTER(i.IDMEDIADOR,'-'),4,'0')  as COD_SUBCLAVE,
	100.00  as PORC_INTERMEDIACION ,
	i.FECHA_EFECTO as FECHA_INI,
	i.FECHA_VENCIMIENTO as FECHA_FIN,
	NULL as P_ESPECIAL_EMISION,
	NULL as P_ESPECIAL_RENOVACION,
	i.IDFISCAL_TOMADOR,
	i.NOMBRE_TOMADOR,
	NULL as FECHA_EFECTO_TRASPASO,
	1 as MEDIADOR_PRINCIPAL_CIC,
	1 AS ACTIVO,
	CURRENT_TIMESTAMP as CREATEDATE,
	CURRENT_TIMESTAMP as MODIF_DATE,
	'MANUAL_CIC' as MODIF_USER,
	BATCHNAME as MODIF_SOURCE

from EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST i
where NUM_AVAL_FIANZA=15846 and BATCHNAME='2111_xxxxxxxxxx'

-----------------------------------------------------------------------------------
-- Actualizar registros de CARTERA que no son válidos
-----------------------------------------------------------------------------------
UPDATE EXT.CARTERA set ACTIVO=0, MODIF_DATE=CURRENT_TIMESTAMP, MODIF_USER='MANUAL'  where NUM_POLIZA=xxx AND NUM_ANUALIDAD=x

-----------------------------------------------------------------------------------
-- REPROCESAR MOVIMIENTOS DE RECIBO INDIVIDUALES
-----------------------------------------------------------------------------------
--///////////////////////////////////////////////////////////////////////
-- LOCALIZAR MOVIMIENTOS RECIBO Y REPROCESAR INDIVIDUALMENTE
--///////////////////////////////////////////////////////////////////////
Select ID, FECHA_DATOS, COD_OPERACION, NUM_RECIBO, NUM_MVTO, DESC_MVTO, FECHA_EFECTO_ANUALIDAD, IMPORTE_TOTAL_RECIBO, DESC_SITUACION_RECIBO, NOMBRE_EMPRESA, COD_RIESGO, IMPORTE_MVTO_RIESGO, ESTADOREG
 FROM  EXT.EXT_MOVIMIENTO_RECIBOS_HIST where COD_OPERACION like '%34109119399%' AND NUM_RECIBO = xxx

-- Obtener los ID de los registros a reprocesar y concatenar con comas (sin espacios) y llamar procedimietno
--call "EXT"."SP_REPROCESO_MOVIMIENTO_RECIBOS"('501633,542194')
call "EXT"."SP_REPROCESO_MOVIMIENTO_RECIBOS"('ID1,ID2,....')

--CONSULTAR RESULTADOS
select * from EXT.CSE_DEBUG where DATETIME > '2024-07-31 12:50'
 

 