DO BEGIN

	
	--PREPARAR BKP
	--TRUNCATE TABLE EXT.CARTERA_BKP_SMM;
	
	TRUNCATE TABLE EXT.CARTERA;
	INSERT INTO EXT.CARTERA SELECT * FROM EXT.CARTERA_BKP_SMM;
	
	--AJUSTAR RELASUJE
	-- UPDATE EXT.RELASUJE SET POSITIONNAME = '4439-0000' WHERE COD_AGENT = 151457144;
	--CALL EXT.SP_REVISION_CARTERA();
	
	--BORRAR EXPEDIENTES_MANUALES
	DELETE FROM EXT.CARTERA WHERE 1=1
	AND RAMO = 'CAUCION'
	AND MODIF_USER LIKE '%EXPEDIENTE%'
	AND NUM_FIANZA IS NULL
	;
	
	SELECT * FROM EXT.CARTERA WHERE 1=1
	AND RAMO = 'CAUCION'
	AND MODIF_USER NOT LIKE '%EXPEDIENTE%'
	AND NUM_FIANZA IS NULL
	;

	--RELASUJE CAUCION
	SELECT * FROM EXT.RELASUJE WHERE LPAD(MOD,3,0) IN ('098','091') AND NUM_POLIZA = 1006727;
	
	INSERT INTO EXT.CARTERA(RAMO
		, NUM_POLIZA
		, IDPRODUCT
		, IDMODALIDAD
		, NUM_ANUALIDAD
		, FECHA_INICIO
		, FECHA_FIN
		, IDPAIS
		, MODIF_USER
    	, P_INTERMEDIACION
    	, COD_MEDIADOR
    	, COD_SUBCLAVE
    	, NUM_EXPEDIENTE
		, CREATEDATE
		, ACTIVO
    	)
	SELECT 'CAUCION'
		, NUM_POLIZA
    	, '' IDPRODUCT
		, MOD
    	, 0 NUM_ANUALIDAD
		, COALESCE(FEC_INI,'1990-12-31')
	    , CASE WHEN FEC_FIN = '0000-00-00' THEN '2200-01-01'
	    	ELSE COALESCE(FEC_FIN,'2200-01-01')
	    	END FECHA_FIN
		, CASE WHEN PAIS = 'ESP' THEN 116
			WHEN PAIS = 'PRT' THEN 112 
			END IDPAIS
        , 'EXPEDIENTE-RELASUJE'
        , CAST(REPLACE(INTERMEDIA, '%', '') AS DECIMAL(6,3))
        , SUBSTRING(POSITIONNAME,1,4) COD_MEDIADOR
        , RIGHT(POSITIONNAME,4) COD_SUBCLAVE
		, NUM_POLIZA
		, CURRENT_TIMESTAMP
		, 1 --ACTIVO
	FROM EXT.RELASUJE R
	WHERE LPAD(MOD,3,0) IN ('091','098')
	AND NOT EXISTS (SELECT 1 FROM EXT.CARTERA C WHERE C.RAMO = 'CAUCION' AND C.NUM_FIANZA IS NULL AND C.MODIF_USER NOT LIKE '%EXPEDIENTE%' AND C.NUM_POLIZA = R.NUM_POLIZA)
	;
	
	SELECT * FROM EXT.CARTERA WHERE NUM_FIANZA IS NULL;
	
	-- SELECT DISTINCT IDMODALIDAD FROM EXT.CARTERA WHERE RAMO = 'CAUCION';
	
	SELECT * FROM CS_PIPELINERUN ORDER BY STARTTIME DESC;

END;



SELECT C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.P_INTERMEDIACION,C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE MEDIADOR
, LPAD(C.IDMODALIDAD,3,0) MODALIDAD_CARTERA
, CASE 
	WHEN R.NUM_POLIZA IS NULL THEN 'NO'
	ELSE 'SI'
END EN_RELASUJE
,R.POSITIONNAME,LPAD(R.MOD,3,0) MODALIDAD_RELASUJE
, CASE
	WHEN  R.NUM_POLIZA IS NULL THEN '-'
	ELSE CASE
			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'SI'
			ELSE 'NO'
		END
END MISMO_MEDIADOR
, CASE	
	WHEN  R.NUM_POLIZA IS NULL THEN 'PÓLIZA NO EXISTE EN RELASUJE'
	ELSE CASE
			WHEN R.POSITIONNAME IS NULL THEN 'MEDIADOR NULL EN RELASUJE'
			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'COINCIDE MEDIADOR'
			WHEN C.COD_MEDIADOR = SUBSTRING(R.POSITIONNAME,1,4) AND C.COD_SUBCLAVE != SUBSTRING(R.POSITIONNAME,5,9) THEN 'DISTINTA SUBCLAVE'
			WHEN (SELECT COUNT(*) FROM EXT.RELASUJE RJ WHERE RJ.NUM_POLIZA = C.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(RJ.MOD,3,0)) > 1 THEN 'VARIOS MEDIADORES EN RELASUJE'
			ELSE 'DISTINTO MEDIADOR'
		END
END TIPO_CASO
FROM EXT.CARTERA C
LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0)
LEFT JOIN (SELECT *
						,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
					FROM EXT.CARTERA CR 
					WHERE  ACTIVO > 0
					AND RAMO = 'CREDITO'
					--AND CR.NUM_POLIZA = V_NUM_POLIZA
					) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND CRT.COD_MEDIADOR = C.COD_MEDIADOR AND CRT.COD_SUBCLAVE = C.COD_SUBCLAVE  AND CRT.NUM_ANUALIDAD = C.NUM_ANUALIDAD
WHERE C.ACTIVO > 0
AND C. RAMO = 'CREDITO'
AND CRT.RN = 1
UNION ALL
SELECT C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.P_INTERMEDIACION,C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE MEDIADOR
, LPAD(C.IDMODALIDAD,3,0) MODALIDAD_CARTERA
, CASE 
	WHEN R.NUM_POLIZA IS NULL THEN 'NO'
	ELSE 'SI'
END EN_RELASUJE
,R.POSITIONNAME,LPAD(R.MOD,3,0) MODALIDAD_RELASUJE
, CASE
	WHEN  R.NUM_POLIZA IS NULL THEN '-'
	ELSE CASE
			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'SI'
			ELSE 'NO'
		END
END MISMO_MEDIADOR
, CASE	
	WHEN  R.NUM_POLIZA IS NULL THEN 'PÓLIZA NO EXISTE EN RELASUJE'
	ELSE CASE
			WHEN R.POSITIONNAME IS NULL THEN 'MEDIADOR NULL EN RELASUJE'
			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'COINCIDE MEDIADOR'
			WHEN C.COD_MEDIADOR = SUBSTRING(R.POSITIONNAME,1,4) AND C.COD_SUBCLAVE != SUBSTRING(R.POSITIONNAME,5,9) THEN 'DISTINTA SUBCLAVE'
			WHEN (SELECT COUNT(*) FROM EXT.RELASUJE RJ WHERE RJ.NUM_POLIZA = C.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(RJ.MOD,3,0)) > 1 THEN 'VARIOS MEDIADORES EN RELASUJE'
			ELSE 'DISTINTO MEDIADOR'
		END
END TIPO_CASO
FROM EXT.CARTERA C
LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0) AND LPAD(R.MOD,3,0) IN ('091','098')
WHERE C.RAMO = 'CAUCION'
AND C.NUM_FIANZA IS NULL
ORDER BY C.NUM_POLIZA