CREATE OR REPLACE FUNCTION EXT.GET_REGISTRO_CARTERA_PORCENTAJE_PLAN(MODALIDAD	VARCHAR(250), NUM_POLIZA VARCHAR(250), COD_MEDIADOR VARCHAR(250), COD_SUBCLAVE VARCHAR(250)) 
	RETURNS TABLE (RAMO NVARCHAR(250),IDPRODUCT NVARCHAR(250), IDSUBMODALIDAD NVARCHAR(250), NUM_FIANZA NVARCHAR(250)
		, NUM_EXPEDIENTE NVARCHAR(250), P_INTERMEDIACION NVARCHAR(250),NUM_ANUALIDAD NVARCHAR(250), ACTIVO NVARCHAR(250), P_ESPECIAL_EMISION NVARCHAR(250)
		, P_ESPECIAL_RENOVACION NVARCHAR(250), P_EMISION NVARCHAR(250), P_RENOVACION NVARCHAR(250), P_EMISION_DEF NVARCHAR(250) , P_RENOVACION_DEF NVARCHAR(250)
		, P_EMISION_FIN NVARCHAR(250), P_RENOV_FIN NVARCHAR(250)) LANGUAGE SQLSCRIPT 
	AS
	BEGIN
		RETURN SELECT  TOP 1 
			C.RAMO, C.IDPRODUCT,
			C.IDSUBMODALIDAD, C.NUM_FIANZA,	C.NUM_EXPEDIENTE,
			C.P_INTERMEDIACION,
			C.NUM_ANUALIDAD, C.ACTIVO,
			C.P_ESPECIAL_EMISION, C.P_ESPECIAL_RENOVACION,
			PC.P_EMISION, PC.P_RENOVACION,
			P.P_EMISION_DEF, P.P_RENOVACION_DEF,
			CASE WHEN C.P_ESPECIAL_EMISION is null or C.P_ESPECIAL_EMISION = 0 
    			THEN CASE WHEN PC.P_EMISION is null Then P.P_EMISION_DEF ELSE PC.P_EMISION END
    			ELSE C.P_ESPECIAL_EMISION END as P_EMISION_FIN,
			CASE WHEN C.P_ESPECIAL_RENOVACION is null or C.P_ESPECIAL_RENOVACION = 0 
    			THEN CASE WHEN PC.P_RENOVACION is null Then P.P_RENOVACION_DEF ELSE PC.P_RENOVACION END
    			ELSE C.P_ESPECIAL_RENOVACION END as P_RENOV_FIN		
    	FROM EXT.CARTERA C
    		LEFT JOIN EXT.PLAN_COMISIONAMIENTO PC ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = PC.POSITIONNAME and C.IDPRODUCT = PC.IDPRODUCT 
    			and C.FECHA_EFECTO >= PC.EFFECTIVESTARTDATE and C.FECHA_EFECTO < PC.EFFECTIVEENDDATE 
    		LEFT JOIN EXT.PRODUCTOS_VW P ON C.IDPRODUCT = P.IDPRODUCT 
    	WHERE IDMODALIDAD=MODALIDAD and NUM_POLIZA=NUM_POLIZA and 
    			COD_MEDIADOR=COD_MEDIADOR and COD_SUBCLAVE=COD_SUBCLAVE
		ORDER BY NUM_ANUALIDAD desc, ACTIVO desc;
		
	END;

