--QUERY PARA OBTENER RELACIÓN GERENTE CANTAL - PARTICIPANTE
SELECT 
    P.USERID,
    GC.USERID,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM CSI_PROXYRELATION PXY
            JOIN CSI_USER SRC ON PXY.SOURCEUSERSEQ = SRC.USERSEQ
            JOIN CSI_USER PROXY ON PXY.PROXYUSERSEQ = PROXY.USERSEQ
            WHERE PROXY.USERID = GC.USERID AND P.USERID = SRC.USERID
        ) 
        THEN 'EXISTE PROXY' 
        ELSE 'NO EXISTE PROXY' 
    END AS PROXY,
    GC.GERENTE_CANAL,
    GC.USERID AS USER_ID_GC,
    P.USERID AS PARTICIPANTE_USERID,
    P.PARTICIPANTE
FROM (
    -- Subconsulta para obtener datos de GERENTE_CANAL y otros atributos
    SELECT 
        UPPER(pa.FIRSTNAME || ' ' || PA.LASTNAME) AS GERENTE_CANAL,
        USERID,
        PA.GENERICATTRIBUTE4
    FROM TCMP.CS_PARTICIPANT pa
    LEFT JOIN TCMP.CS_POSITION po 
        ON pa.PAYEESEQ = po.PAYEESEQ 
        AND po.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd') 
        AND po.ISLAST = 1
    LEFT JOIN TCMP.CS_PROCESSINGUNIT pu 
        ON po.PROCESSINGUNITSEQ = pu.PROCESSINGUNITSEQ
    WHERE 
        pa.genericboolean4 = 1 
        AND pa.ISLAST = 1 
        AND pa.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd') 
        AND pu.NAME = 'Spain'
) GC
LEFT JOIN (
    -- Subconsulta para obtener datos de PARTICIPANTE
    SELECT 
        UPPER(pa.GENERICATTRIBUTE12) AS GERENTE_CANAL,
        USERID,
        PA.GENERICATTRIBUTE4,
        CASE 
            WHEN PA.FIRSTNAME IS NULL THEN PA.LASTNAME 
            ELSE PA.FIRSTNAME || ' ' || PA.LASTNAME 
        END AS PARTICIPANTE
    FROM TCMP.CS_PARTICIPANT pa
    LEFT JOIN TCMP.CS_POSITION po 
        ON pa.PAYEESEQ = po.PAYEESEQ 
        AND po.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd') 
        AND po.ISLAST = 1
    LEFT JOIN TCMP.CS_PROCESSINGUNIT pu 
        ON po.PROCESSINGUNITSEQ = pu.PROCESSINGUNITSEQ
    WHERE 
        PA.GENERICATTRIBUTE12 IS NOT NULL
        AND pa.ISLAST = 1 
        AND pa.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd') 
        AND pu.NAME = 'Spain'
) P 
ON GC.GERENTE_CANAL = P.GERENTE_CANAL
-- WHERE 1 = (CASE WHEN EXISTS (SELECT 1 
-- 		FROM CSI_PROXYRELATION PXY
-- 		JOIN CSI_USER SRC ON PXY.SOURCEUSERSEQ = SRC.USERSEQ
-- 		JOIN CSI_USER PROXY ON PXY.PROXYUSERSEQ = PROXY.USERSEQ 
-- 		WHERE PROXY.USERID = GC.USERID AND P.USERID = SRC.USERID
-- 	) THEN '0' ELSE '1' END )
;