SELECT 
	CASE WHEN PA.FIRSTNAME IS NULL THEN UPPER(COALESCE(PA.LASTNAME,'')) ELSE UPPER(PA.FIRSTNAME || ' ' || PA.LASTNAME) END PARTICIPANT
	, CASE WHEN COALESCE(PA.GENERICBOOLEAN4,0) = 1 THEN 'SI' ELSE 'NO' END ES_GERENTE_CANAL
	, PA.USERID
	, PA.GENERICATTRIBUTE2 IDPARTICIPANT
	, CASE WHEN COALESCE(PA.GENERICATTRIBUTE12,'') = '' THEN 'NO' ELSE 'SI' END TIENE_GERENTE_CANAL_ASIGNADO
	, UPPER(PA.GENERICATTRIBUTE12) GERENTE_CANTAL
	, GC.USERID ID_GERENTE_CANAL
	-- , PROXY.SOURCEUSERSEQ SOURCEUSERSEQ
	-- , PROXY.PROXYUSERSEQ PROXYUSERSEQ
	, CASE
		WHEN PROXY.SOURCEUSERSEQ IS NULL THEN 'NO TIENE PROXY CON NADIE'
	 	WHEN EXISTS(SELECT 1 FROM CSI_USER U INNER JOIN CS_PARTICIPANT P ON U.USERID = P.USERID WHERE U.USERSEQ = PROXY.PROXYUSERSEQ AND P.GENERICBOOLEAN4 = 1) 
	 		THEN 'CON GERENTE CANAL'
	 		ELSE 'NO CON GERENTE CANAL'
	 --	WHEN EXISTS(SELECT 1 FROM CSI_USER WHERE USERSEQ = PROXY.PROXYUSERSEQ AND USERID = GC.USERID) THEN 'CON GERENTE CANAL'
	END TIPO_PROXY
-- , CASE 
-- 	WHEN EXISTS(SELECT 1 FROM CSI_USER WHERE USERSEQ = PROXY.PROXYUSERSEQ AND USERID = GC.USERID) 
-- 		THEN GC.GERENTE_CANAL
-- 		ELSE (SELECT CASE WHEN FIRSTNAME IS NULL THEN UPPER(COALESCE(LASTNAME,'')) ELSE UPPER(FIRSTNAME || ' ' || LASTNAME) END FROM CSI_USER WHERE USERSEQ = PROXY.PROXYUSERSEQ)
--   END PROXY_CON
	, PRX.USERID ID_PROXY_CON
FROM CS_PARTICIPANT PA
LEFT JOIN CS_POSITION PO ON PA.PAYEESEQ = PO.PAYEESEQ
LEFT JOIN TCMP.CS_PROCESSINGUNIT PU ON PO.PROCESSINGUNITSEQ = PU.PROCESSINGUNITSEQ 
INNER JOIN (
        SELECT UPPER(pa.FIRSTNAME || ' ' || PA.LASTNAME) AS GERENTE_CANAL,
            USERID,
            PA.GENERICATTRIBUTE4
        FROM TCMP.CS_PARTICIPANT pa
            LEFT JOIN TCMP.CS_POSITION po ON pa.PAYEESEQ = po.PAYEESEQ
            AND po.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            AND PO.EFFECTIVEENDDATE = TO_DATE('22000101', 'yyyymmdd')
            AND po.ISLAST = 1
            LEFT JOIN TCMP.CS_PROCESSINGUNIT pu ON po.PROCESSINGUNITSEQ = pu.PROCESSINGUNITSEQ
        WHERE pa.genericboolean4 = 1
            AND pa.ISLAST = 1
            AND pa.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            AND pu.NAME = 'Spain'
    ) GC ON GC.GERENTE_CANAL = UPPER(PA.GENERICATTRIBUTE12)
LEFT JOIN CSI_USER SRC ON SRC.USERID = PA.USERID
LEFT JOIN CSI_PROXYRELATION PROXY ON PROXY.SOURCEUSERSEQ = SRC.USERSEQ
LEFT JOIN CSI_USER PRX ON PRX.USERSEQ = PROXY.PROXYUSERSEQ
WHERE -- PARTICIPANT ACTIVO
PA.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
AND PA.ISLAST = 1
--POSITION ACTIVO
AND PO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
AND PO.ISLAST = 1
AND PO.PROCESSINGENDDATE = TO_DATE('22000101', 'yyyymmdd')

-- -- BU SPAIN
AND PU.NAME = 'Spain'
AND PA.USERID = 'A28109247'
ORDER BY PA.USERID 
;

SELECT * FROM CSI_USER WHERE USERSEQ IN (80,1512,1901);
SELECT * FROM CSI_PROXYRELATION WHERE SOURCEUSERSEQ = 1517;

SELECT UPPER(pa.FIRSTNAME || ' ' || PA.LASTNAME) AS GERENTE_CANAL,
            USERID,
            PA.GENERICATTRIBUTE4
            ,*
        FROM TCMP.CS_PARTICIPANT pa
            LEFT JOIN TCMP.CS_POSITION po ON pa.PAYEESEQ = po.PAYEESEQ
            AND po.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            AND po.ISLAST = 1
            AND PO.EFFECTIVEENDDATE = TO_DATE('22000101', 'yyyymmdd')
            LEFT JOIN TCMP.CS_PROCESSINGUNIT pu ON po.PROCESSINGUNITSEQ = pu.PROCESSINGUNITSEQ
        WHERE pa.genericboolean4 = 1
            AND pa.ISLAST = 1
            AND pa.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            AND pu.NAME = 'Spain'
            AND PA.USERID = 'ipellico@cesce.es';