SELECT PA.USERID USERID_PARTICIPANT,
UPPER(COALESCE(PA.FIRSTNAME,'')||' '||COALESCE(PA.LASTNAME,'')) PARTICIPANT, PA.GENERICATTRIBUTE12 GERENTE_CANAL
,GC.USERID ID_GERENTE_CANAL
,PROXY.USERSEQ PROXY_USERSEQ,PROXY.USERID PROXY_USERID,UPPER(COALESCE(PROXY.FIRSTNAME,'') || ' ' || COALESCE(PROXY.LASTNAME,'')) PROXY,PROXY.GENERICBOOLEAN4 ES_GERENTE_CANAL
-- ,SRC.USERID
,CASE WHEN GC.USERID = PROXY.USERID THEN 'PROXY ES SU GERENTE' ELSE 'PROXY NO ES SU GERENTE' END 
FROM CS_PARTICIPANT PA
LEFT JOIN CS_POSITION PO ON PA.PAYEESEQ = PO.PAYEESEQ
            AND PO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            AND PO.ISLAST = 1
LEFT JOIN TCMP.CS_PROCESSINGUNIT PU ON PO.PROCESSINGUNITSEQ = PU.PROCESSINGUNITSEQ 
LEFT JOIN (SELECT UPPER(COALESCE(PA1.FIRSTNAME,'')||' '||COALESCE(PA1.LASTNAME,'')) GERENTE_CANAL,PA1.USERID 
			FROM CS_PARTICIPANT PA1 
			LEFT JOIN CS_POSITION PO1 ON PA1.PAYEESEQ = PO1.PAYEESEQ 
            	AND PO1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
            	AND PO1.ISLAST = 1
			LEFT JOIN TCMP.CS_PROCESSINGUNIT PU1 ON PO1.PROCESSINGUNITSEQ = PU1.PROCESSINGUNITSEQ 
			WHERE PA1.ISLAST = 1
			AND PA1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
			AND PU1.NAME = 'Spain' AND COALESCE(PA1.GENERICBOOLEAN4,0) = 1) GC ON GC.GERENTE_CANAL = UPPER(PA.GENERICATTRIBUTE12)
LEFT JOIN CSI_USER SRC ON SRC.USERID = PA.USERID
        LEFT JOIN CSI_PROXYRELATION PXY ON PXY.SOURCEUSERSEQ = SRC.USERSEQ
        LEFT JOIN (SELECT PA.USERID,U.USERSEQ,U.FIRSTNAME,U.LASTNAME,PA.GENERICBOOLEAN4
        	FROM CS_PARTICIPANT PA LEFT JOIN CSI_USER U ON PA.USERID = U.USERID --AND PA.GENERICBOOLEAN4 = 1
        	WHERE PA.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
        	AND PA.ISLAST = 1) PROXY ON PROXY.USERSEQ = PXY.PROXYUSERSEQ 
WHERE PA.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
AND PA.ISLAST = 1
AND PU.NAME = 'Spain'
--AND PA.USERID IN ('B17268491-0001','raulcabrera@cesce.es')
AND COALESCE(PA.GENERICBOOLEAN4,0) = 0
AND 1 = CASE WHEN GC.USERID = PROXY.USERID THEN 0 ELSE 1 END 
AND COALESCE(PROXY.GENERICBOOLEAN4,0) = 1
;