CREATE OR REPLACE PROCEDURE EXT.SP_ARREGLAR_CARTERA_RELASUJE()
LANGUAGE SQLSCRIPT 
SQL SECURITY DEFINER DEFAULT SCHEMA "EXT" AS 
BEGIN 

	DECLARE i_Tenant VARCHAR(127);
	DECLARE cVersion CONSTANT VARCHAR(2) := '01';
	DECLARE v_proc_name VARCHAR2(50) := ::CURRENT_OBJECT_NAME;
	DECLARE io_contador INTEGER := 0;
	DECLARE v_contador INTEGER := 0;
	
	--CONTROLADOR DE EXCEPCIONES
    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN	
	    CALL LIB_GLOBAL_CESCE :w_debug (
	            i_Tenant,
	            v_proc_name || '. SQL ERROR_MESSAGE: ' || IFNULL( ::SQL_ERROR_MESSAGE, '') || '. SQL_ERROR_CODE: ' ||  ::SQL_ERROR_CODE,
	            v_proc_name,
	            io_contador
	        );
         --RESIGNAL;
    END;
    
    --OBTENER TENANT
	SELECT TENANTID INTO i_Tenant FROM CS_TENANT;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'STARTING with SESSION_USER: ' || SESSION_USER || ' version ' || cVersion,v_proc_name,io_contador);
	
	--CREACIÓN DE TABLAS DE BKP PARA PRUEBAS
	-- TRUNCATE TABLE EXT.CARTERA;
	-- INSERT INTO EXT.CARTERA SELECT * FROM EXT.CARTERA_BKP_TEST;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'ELIMINAMOS EXPEDIENTES GENERADOS MANUALMENTE',v_proc_name,io_contador);
	
	--ELIMINO EXPEDIENTES MANUALES
	DELETE FROM EXT.CARTERA WHERE MODIF_USER = 'MANUAL-EXPEDIENTE' AND NUM_FIANZA IS NULL;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ELIMINAR EXPEDIENTES GENERADOS MANUALMENTE. REGISTROS ELIMINADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'GENERAMOS EXPEDIENTES MANUALMENTE A PARTIR DE RELASUJE',v_proc_name,io_contador);
	
	
	--CREACIÓN DE EXPEDIENTES
	INSERT INTO EXT.CARTERA(RAMO
		, NUM_POLIZA
		, IDPRODUCT
		, IDMODALIDAD
		, NUM_ANUALIDAD
		, FECHA_INICIO
		, FECHA_FIN
		, IDPAIS
		, MODIF_USER
    	, P_INTERMEDIACION
    	, COD_MEDIADOR
    	, COD_SUBCLAVE
    	, NUM_EXPEDIENTE
		, CREATEDATE
		, ACTIVO
    	)
	SELECT 'CAUCION'
		, NUM_POLIZA
    	, '' IDPRODUCT
		, MOD
    	, 0 NUM_ANUALIDAD
		, COALESCE(FEC_INI,'1990-12-31')
	    , CASE WHEN FEC_FIN = '0000-00-00' THEN '2200-01-01'
	    	ELSE COALESCE(FEC_FIN,'2200-01-01')
	    	END FECHA_FIN
		, CASE WHEN PAIS = 'ESP' THEN 116
			WHEN PAIS = 'PRT' THEN 112 
			END IDPAIS
        , 'EXPEDIENTE-RELASUJE'
        , INTERMEDIA
        , SUBSTRING(POSITIONNAME,1,4) COD_MEDIADOR
        , RIGHT(POSITIONNAME,4) COD_SUBCLAVE
		, NUM_POLIZA
		, CURRENT_TIMESTAMP
		, 1 --ACTIVO
	FROM EXT.RELASUJE R
	WHERE LPAD(MOD,3,0) IN ('091','098')
	-- AND NOT EXISTS (SELECT 1 FROM EXT.CARTERA C WHERE C.RAMO = 'CAUCION' AND C.NUM_FIANZA IS NULL AND C.MODIF_USER NOT LIKE '%EXPEDIENTE%' AND C.NUM_POLIZA = R.NUM_POLIZA)
	AND NUM_POLIZA NOT IN (SELECT NUM_POLIZA FROM EXT.CARTERA C WHERE C.RAMO = 'CAUCION' AND C.NUM_FIANZA IS NULL /*AND C.MODIF_USER NOT LIKE '%EXPEDIENTE%' */AND C.NUM_POLIZA = R.NUM_POLIZA)
	;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN GENERAR EXPEDIENTES MANUALMENTE A PARTIR DE RELASUJE. REGISTROS GENERADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	--ELIMINAMOS DUPLICADOS
	
	-- TEMP_CREDITO = SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE,COUNT(*)
	-- 		FROM EXT.CARTERA
	-- 		WHERE RAMO = 'CREDITO'
	-- 		AND ACTIVO > 0
	-- 		GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
	-- 		HAVING COUNT(*) > 1
	-- 		ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
	
	-- IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= 'EXT' and TABLE_NAME = 'CARTERA_BKP_TEST_INICIO_CREDITO') IS NULL THEN
 --       CREATE COLUMN TABLE EXT.CARTERA_BKP_TEST_INICIO_CREDITO AS (SELECT * FROM EXT.CARTERA WHERE 1=0);
	-- END IF;
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'CREACION TABLA TEST-CARTERA_BKP_TEST_INICIO_CREDITO ',v_proc_name,io_contador);
	-- TRUNCATE TABLE EXT.CARTERA_BKP_TEST_INICIO_CREDITO;
	
	-- INSERT INTO EXT.CARTERA_BKP_TEST_INICIO_CREDITO
	-- SELECT *
	-- FROM EXT.CARTERA
	-- 	WHERE (NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CREDITO)
	-- 		AND ACTIVO > 0
	-- 	ORDER BY NUM_POLIZA,NUM_ANUALIDAD; 
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN CREACION TABLA TEST-CARTERA_BKP_TEST_INICIO_CREDITO. REGISTROS INSERTADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	-- TEMP_CAUCION = SELECT NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,COUNT(*)
	-- 			FROM EXT.CARTERA
	-- 			WHERE RAMO = 'CAUCION'
	-- 			AND ACTIVO > 0
	-- 			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
	-- 			HAVING COUNT(*) > 1
	-- 			ORDER BY NUM_POLIZA,NUM_FIANZA;
	
	-- IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= 'EXT' and TABLE_NAME = 'CARTERA_BKP_TEST_INICIO_CAUCION') IS NULL THEN
    --     CREATE COLUMN TABLE EXT.CARTERA_BKP_TEST_INICIO_CAUCION AS (SELECT * FROM EXT.CARTERA WHERE 1=0);
	-- END IF;
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'CREACION TABLA TEST-CARTERA_BKP_TEST_INICIO_CAUCION ',v_proc_name,io_contador);
	
	-- TRUNCATE TABLE EXT.CARTERA_BKP_TEST_INICIO_CAUCION;
	
	-- INSERT INTO EXT.CARTERA_BKP_TEST_INICIO_CAUCION
	-- SELECT *
	-- FROM EXT.CARTERA
	-- WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CAUCION)
	-- 	AND ACTIVO > 0
	-- 	AND NUM_FIANZA IS NOT NULL
	-- ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN CREACION TABLA TEST-CARTERA_BKP_TEST_INICIO_CAUCION. REGISTROS INSERTADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'ELIMINAMOS DUPLICADOS. PROCEDIMIENTO SP_CORREGIR_POLIZAS_DUPLICADAS_PRD',v_proc_name,io_contador);
	-- --PROCEDIMIENTO ELIMINAR DUPLICADOS
	-- CALL EXT.SP_CORREGIR_POLIZAS_DUPLICADAS_PRD();
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ELIMINAR DUPLICADOS. PROCEDIMIENTO SP_CORREGIR_POLIZAS_DUPLICADAS_PRD',v_proc_name,io_contador);
	

	-- --FINAL	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'CREACION TABLA TEST-CARTERA_BKP_TEST_FINAL_CREDITO ',v_proc_name,io_contador);
	-- IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= 'EXT' and TABLE_NAME = 'CARTERA_BKP_TEST_FINAL_CREDITO') IS NULL THEN
    --     CREATE COLUMN TABLE EXT.CARTERA_BKP_TEST_FINAL_CREDITO AS (SELECT * FROM EXT.CARTERA WHERE 1=0);
	-- END IF;
	
	-- TRUNCATE TABLE EXT.CARTERA_BKP_TEST_FINAL_CREDITO;
	
	-- INSERT INTO EXT.CARTERA_BKP_TEST_FINAL_CREDITO
	-- SELECT *
	-- FROM EXT.CARTERA
	-- 	WHERE (NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE 
	-- 																				FROM :TEMP_CREDITO)
	-- 		AND ACTIVO > 0
	-- 	ORDER BY NUM_POLIZA,NUM_ANUALIDAD; 
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN CREACION TABLA TEST-CARTERA_BKP_TEST_FINAL_CREDITO. REGISTROS INSERTADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'CREACION TABLA TEST-CARTERA_BKP_TEST_FINAL_CAUCION ',v_proc_name,io_contador);
	-- IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= 'EXT' and TABLE_NAME = 'CARTERA_BKP_TEST_FINAL_CAUCION') IS NULL THEN
    --     CREATE COLUMN TABLE EXT.CARTERA_BKP_TEST_FINAL_CAUCION AS (SELECT * FROM EXT.CARTERA WHERE 1=0);
	-- END IF;
	-- TRUNCATE TABLE EXT.CARTERA_BKP_TEST_FINAL_CAUCION;
	
	-- INSERT INTO EXT.CARTERA_BKP_TEST_FINAL_CAUCION
	-- SELECT *
	-- FROM EXT.CARTERA
	-- WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE 
	-- 																			FROM :TEMP_CAUCION)
	-- 	AND ACTIVO > 0
	-- 	AND NUM_FIANZA IS NOT NULL
	-- ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN CREACION TABLA TEST-CARTERA_BKP_TEST_FINAL_CAUCION. REGISTROS INSERTADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	-- -- SELECT * FROM EXT.CARTERA
	-- -- WHERE MODIF_USER = 'MANUAL - NO EXISTE RELASUJE'
	-- -- ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_ANUALIDAD;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'INICIO RESUMEN',v_proc_name,io_contador);
	--------------------------------------------------------------------------------------------------
	------------------------ TIPOS DE CASOS EN CARTERA -- --------------------------------------------
	------- 1: PÓLIZA NO EXISTE EN RELASUJE
	-------	2: MEDIADOR NULL EN RELASUJE
	-------	3: COINCIDE MEDIADOR
	-------	4: DISTINTA SUBCLAVE
	-------	5: VARIOS MEDIADORES EN RELASUJE
	-------	6: DISTINTO MEDIADOR
	--------------------------------------------------------------------------------------------------
	-- TEMP_CARTERA_EXCEL = SELECT C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA
	-- 	,C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE MEDIADOR
	-- 	, LPAD(C.IDMODALIDAD,3,0) MODALIDAD_CARTERA
	-- 	, CASE 
	-- 		WHEN R.NUM_POLIZA IS NULL THEN 'NO'
	-- 		ELSE 'SI'
	-- 	END EN_RELASUJE
	-- 	,R.POSITIONNAME,LPAD(R.MOD,3,0) MODALIDAD_RELASUJE
	-- 	, CASE
	-- 		WHEN  R.NUM_POLIZA IS NULL THEN '-'
	-- 		ELSE CASE
	-- 			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'SI'
	-- 			ELSE 'NO'
	-- 			END
	-- 	END MISMO_MEDIADOR
	-- 	, CASE	
	-- 		WHEN  R.NUM_POLIZA IS NULL THEN 'PÓLIZA NO EXISTE EN RELASUJE'
	-- 		ELSE CASE
	-- 			WHEN R.POSITIONNAME IS NULL THEN 'MEDIADOR NULL EN RELASUJE'
	-- 			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'COINCIDE MEDIADOR'
	-- 			WHEN C.COD_MEDIADOR = SUBSTRING(R.POSITIONNAME,1,4) AND C.COD_SUBCLAVE != SUBSTRING(R.POSITIONNAME,5,9) THEN 'DISTINTA SUBCLAVE'
	-- 			WHEN (SELECT COUNT(*) FROM EXT.RELASUJE RJ WHERE RJ.NUM_POLIZA = C.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(RJ.MOD,3,0)) > 1 THEN 'VARIOS MEDIADORES EN RELASUJE'
	-- 			ELSE 'DISTINTO MEDIADOR'
	-- 		END
	-- 	END TIPO_CASO
	-- 	-- , C.MODIF_USER
	-- 	-- , CASE
	-- 	-- 		WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 	-- 		ELSE '-'
	-- 	-- 	END MODIFICADO
	-- 	, CASE
	-- 			-- WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 			WHEN EXISTS(SELECT 1 FROM EXT.CARTERA CR WHERE CR.ACTIVO > 0 AND CR.NUM_POLIZA = C.NUM_POLIZA AND CR.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 			ELSE '-'
	-- 		END MODIFICADO
	-- 		,COALESCE(R.FEC_INI,'1990-12-31') FECHA_INICIO
	-- 		,COALESCE(R.FEC_FIN,'2200-01-01') FECHA_FIN
	-- 	FROM EXT.CARTERA C 
	-- 	LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0)
	-- 	LEFT JOIN (SELECT *
	-- 					,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
	-- 				FROM EXT.CARTERA CR 
	-- 				WHERE  ACTIVO > 0
	-- 				--AND CR.NUM_POLIZA = V_NUM_POLIZA
	-- 				) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND CRT.COD_MEDIADOR = C.COD_MEDIADOR AND CRT.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRT.RN = 1
	-- 	LEFT JOIN (SELECT * FROM EXT.CARTERA CR WHERE CR.RAMO = 'CAUCION' AND CR.NUM_FIANZA IS NOT NULL) CRTC ON C.NUM_POLIZA = CRTC.NUM_POLIZA 
	-- 		AND CRTC.COD_MEDIADOR = C.COD_MEDIADOR AND CRTC.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRTC.NUM_FIANZA = C.NUM_FIANZA
	-- 	WHERE C.ACTIVO > 0
	-- 	-- AND CRTC.NUM_FIANZA IS NOT NULL
	-- 	-- FILTRO RAMO
	-- 	AND 1 = (CASE 
	-- 		WHEN C.RAMO = 'CREDITO' AND CRT.RN=1 THEN 1
	-- 		WHEN C.RAMO = 'CAUCION' THEN 1
	-- 		ELSE 0
	-- 	END)
	-- 	-- FILTRO EXISTEN EN RELASUJE
	-- 	-- AND 1 = (CASE 
	-- 	-- 			WHEN R.NUM_POLIZA IS NOT NULL THEN 1
	-- 	-- 			ELSE 0
	-- 	-- 		END
	-- 	-- )
	-- 	--FILTRO DISTINTOS MEDIADORES
	-- 	-- AND 1 = (CASE
	-- 	-- 		WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE <> COALESCE(R.POSITIONNAME,'') THEN 1
	-- 	-- 		ELSE 0
	-- 	-- 		END
	-- 	-- )
		
	-- 	GROUP BY C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA,C.COD_MEDIADOR,C.COD_SUBCLAVE,R.POSITIONNAME,LPAD(C.IDMODALIDAD,3,0),LPAD(R.MOD,3,0),R.NUM_POLIZA
	-- 	,R.FEC_INI,R.FEC_FIN
	-- 	ORDER BY NUM_POLIZA;
		
	-- 	SELECT * FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CREDITO';
	-- 	SELECT * FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CAUCION';
		
	TEMP_CARTERA = SELECT C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA
		,C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE MEDIADOR
		, LPAD(C.IDMODALIDAD,3,0) MODALIDAD_CARTERA
		, CASE 
			WHEN R.NUM_POLIZA IS NULL THEN 'NO'
			ELSE 'SI'
		END EN_RELASUJE
		,R.POSITIONNAME,LPAD(R.MOD,3,0) MODALIDAD_RELASUJE
		, CASE
			WHEN  R.NUM_POLIZA IS NULL THEN '-'
			ELSE CASE
				WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'SI'
				ELSE 'NO'
				END
		END MISMO_MEDIADOR
		, CASE	
			WHEN  R.NUM_POLIZA IS NULL THEN 1
			ELSE CASE
				WHEN R.POSITIONNAME IS NULL THEN 2
				WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 3
				WHEN C.COD_MEDIADOR = SUBSTRING(R.POSITIONNAME,1,4) AND C.COD_SUBCLAVE != SUBSTRING(R.POSITIONNAME,5,9) THEN 4
				WHEN (SELECT COUNT(*) FROM EXT.RELASUJE RJ WHERE RJ.NUM_POLIZA = C.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(RJ.MOD,3,0)) > 1 THEN 5
				ELSE 6
			END
		END TIPO_CASO
		-- , C.MODIF_USER
		-- , CASE
		-- 		WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
		-- 		ELSE '-'
		-- 	END MODIFICADO
		, CASE
				-- WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
				WHEN EXISTS(SELECT 1 FROM EXT.CARTERA CR WHERE CR.ACTIVO > 0 AND CR.NUM_POLIZA = C.NUM_POLIZA AND CR.MODIF_USER != 'CDL') THEN 'MANUAL'
				ELSE '-'
			END MODIFICADO
			,COALESCE(R.FEC_INI,'1990-12-31') FECHA_INICIO
			,COALESCE(R.FEC_FIN,'2200-01-01') FECHA_FIN
		FROM EXT.CARTERA C 
		LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0)
		LEFT JOIN (SELECT *
						,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
					FROM EXT.CARTERA CR 
					WHERE  ACTIVO > 0
					--AND CR.NUM_POLIZA = V_NUM_POLIZA
					) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND CRT.COD_MEDIADOR = C.COD_MEDIADOR AND CRT.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRT.RN = 1
		LEFT JOIN (SELECT * FROM EXT.CARTERA CR WHERE CR.RAMO = 'CAUCION' AND CR.NUM_FIANZA IS NOT NULL) CRTC ON C.NUM_POLIZA = CRTC.NUM_POLIZA 
			AND CRTC.COD_MEDIADOR = C.COD_MEDIADOR AND CRTC.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRTC.NUM_FIANZA = C.NUM_FIANZA
		WHERE C.ACTIVO > 0
		-- AND CRTC.NUM_FIANZA IS NOT NULL
		-- FILTRO RAMO
		AND 1 = (CASE 
			WHEN C.RAMO = 'CREDITO' AND CRT.RN=1 THEN 1
			WHEN C.RAMO = 'CAUCION' THEN 1
			ELSE 0
		END)
		-- FILTRO EXISTEN EN RELASUJE
		-- AND 1 = (CASE 
		-- 			WHEN R.NUM_POLIZA IS NOT NULL THEN 1
		-- 			ELSE 0
		-- 		END
		-- )
		--FILTRO DISTINTOS MEDIADORES
		-- AND 1 = (CASE
		-- 		WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE <> COALESCE(R.POSITIONNAME,'') THEN 1
		-- 		ELSE 0
		-- 		END
		-- )
		
		GROUP BY C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA,C.COD_MEDIADOR,C.COD_SUBCLAVE,R.POSITIONNAME,LPAD(C.IDMODALIDAD,3,0),LPAD(R.MOD,3,0),R.NUM_POLIZA
		,R.FEC_INI,R.FEC_FIN
		ORDER BY NUM_POLIZA;
		
	
	--------------------------------------------------------------------------------------------------
	------------------------ CASO 1: DESACTIVAR PÓLIZAS QUE NO ESTÁN EN RELASUJE ----------------------
	--------------------------------------------------------------------------------------------------
	
	TEMP_NO_EXISTE_RELASUJE = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 1
		AND RAMO = 'CREDITO' AND MEDIADOR != '0000-0000';
	
	SELECT COUNT(*) INTO v_contador FROM :TEMP_NO_EXISTE_RELASUJE;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS QUE NO EXISTEN EN RELASUJE: ' || v_contador,v_proc_name,io_contador);
	
	-- UPDATE C
	-- SET ACTIVO = 0
	-- , MODIF_USER = MODIF_USER || '-MDF_NO_RELASUJE'
	-- , MODIF_DATE = CURRENT_DATE
	-- FROM EXT.CARTERA C INNER JOIN :TEMP_NO_EXISTE_RELASUJE T ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
	-- 	AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
	-- 	AND C.IDMODALIDAD = T.MODALIDAD_CARTERA
	-- WHERE C.ACTIVO > 0
	-- ;
		
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN NO EXISTEN EN RELASUJE. REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	--------------------------------------------------------------------------------------------------
	------------------------ CASO2: MEDIADOR NULL EN RELASUJE -------------------------------------
	--------------------------------------------------------------------------------------------------
	TEMP_MEDIADOR_NULL_RELASUJE = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 2;
	
	v_contador = 0;
	SELECT COUNT(*) INTO v_contador FROM :TEMP_MEDIADOR_NULL_RELASUJE;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS CON MEDIADOR NULL: ' || v_contador,v_proc_name,io_contador);
	
	
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN . REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	
	
	--------------------------------------------------------------------------------------------------
	------------------------ CASO3: COINCIDE MEDIADOR -------------------------------------
	--------------------------------------------------------------------------------------------------
	TEMP_COINCIDE_MEDIADOR = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 3;
	
	v_contador = 0;
	SELECT COUNT(*) INTO v_contador FROM :TEMP_COINCIDE_MEDIADOR;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS COINCIDE MEDIADOR: ' || v_contador,v_proc_name,io_contador);
	
	SELECT COUNT(*) INTO v_contador FROM :TEMP_COINCIDE_MEDIADOR T INNER JOIN EXT.CARTERA C ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
		AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
		AND C.IDMODALIDAD = T.MODALIDAD_CARTERA AND (C.FECHA_INICIO != T.FECHA_INICIO OR C.FECHA_FIN != T.FECHA_FIN)
	WHERE C.ACTIVO >0;
	
	
	-- SELECT 'DISTINTA FECHA',T.FECHA_INICIO,T.FECHA_FIN,C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_FIANZA,C.NUM_ANUALIDAD,C.FECHA_INICIO,C.FECHA_FIN 
	-- , C.MODIF_SOURCE, C.MODIF_USER
	-- FROM :TEMP_COINCIDE_MEDIADOR T INNER JOIN EXT.CARTERA C ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
	-- 	AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
	-- 	AND C.IDMODALIDAD = T.MODALIDAD_CARTERA AND (C.FECHA_INICIO != T.FECHA_INICIO OR C.FECHA_FIN != T.FECHA_FIN)
	-- WHERE C.ACTIVO >0
	-- AND C.NUM_FIANZA IS NULL
	-- ORDER BY NUM_POLIZA;
	
	
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS COINCIDE MEDIADOR Y NO FECHAS INICIO/FIN ' || v_contador,v_proc_name,io_contador);
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN. REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	UPDATE C
	SET C.FECHA_INICIO = T.FECHA_INICIO
	, C.FECHA_FIN = T.FECHA_FIN
	, C.MODIF_USER = C.MODIF_USER ||'_DST_FEC'
	, C.MODIF_DATE = CURRENT_DATE
	FROM :TEMP_COINCIDE_MEDIADOR T INNER JOIN EXT.CARTERA C ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
		AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
		AND C.IDMODALIDAD = T.MODALIDAD_CARTERA AND (C.FECHA_INICIO != T.FECHA_INICIO OR C.FECHA_FIN != T.FECHA_FIN)
	WHERE C.ACTIVO >0
	AND C.NUM_FIANZA IS NULL;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS COINCIDE MEDIADOR Y NO FECHAS INICIO/FIN. REGISTROS ACTUALIZADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	-- SELECT 'DISTINTA FECHA_V2',T.FECHA_INICIO,T.FECHA_FIN,C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_FIANZA,C.NUM_ANUALIDAD,C.FECHA_INICIO,C.FECHA_FIN 
	-- , C.MODIF_SOURCE, C.MODIF_USER
	-- FROM :TEMP_COINCIDE_MEDIADOR T INNER JOIN EXT.CARTERA C ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
	-- 	AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
	-- 	AND C.IDMODALIDAD = T.MODALIDAD_CARTERA AND (C.FECHA_INICIO != T.FECHA_INICIO OR C.FECHA_FIN != T.FECHA_FIN)
	-- WHERE C.ACTIVO >0
	-- AND C.NUM_FIANZA IS NULL
	-- ORDER BY NUM_POLIZA;
	--------------------------------------------------------------------------------------------------
	------------------------ CASO4: ACTUALIZAR DISTINTA SUBCLAVE -------------------------------------
	--------------------------------------------------------------------------------------------------
	TEMP_DISTINTA_SUBCLAVE = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 4 ;
	
	v_contador = 0;
	SELECT COUNT(*) INTO v_contador FROM :TEMP_DISTINTA_SUBCLAVE;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS CON DISTINTA SUBCLAVE: ' || v_contador,v_proc_name,io_contador);
	
	UPDATE C
	SET COD_SUBCLAVE = RIGHT(T.POSITIONNAME,4)
	, MODIF_USER = MODIF_USER || '-MDF_SUBCLAVE'
	, MODIF_DATE = CURRENT_DATE
	FROM EXT.CARTERA C INNER JOIN :TEMP_DISTINTA_SUBCLAVE T ON C.COD_MEDIADOR ||'-'|| C.COD_SUBCLAVE = T.MEDIADOR
		AND C.RAMO = T.RAMO AND C.NUM_POLIZA = T.NUM_POLIZA AND C.NUM_ANUALIDAD = T.NUM_ANUALIDAD AND C.NUM_FIANZA = T.NUM_FIANZA
		AND C.IDMODALIDAD = T.MODALIDAD_CARTERA
	WHERE C.ACTIVO > 0;
		
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN SUBCLAVES. REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	
	
	--------------------------------------------------------------------------------------------------
	------------------------ CASO5: VARIOS MEDIADORES EN RELASUJE -------------------------------------
	--------------------------------------------------------------------------------------------------
	TEMP_VARIOS_MEDIADORES_RELASUJE = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 5;
	
	v_contador = 0;
	SELECT COUNT(*) INTO v_contador FROM :TEMP_VARIOS_MEDIADORES_RELASUJE;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS CON VARIOS MEDIADORES RELASUJE: ' || v_contador,v_proc_name,io_contador);
	
	
		
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN . REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	
	
	--------------------------------------------------------------------------------------------------
	------------------------ CASO6: DISTINTO MEDIADOR -------------------------------------
	--------------------------------------------------------------------------------------------------
	TEMP_DISTINTO_MEDIADOR = SELECT * FROM :TEMP_CARTERA WHERE TIPO_CASO = 6;
	
	v_contador = 0;
	SELECT COUNT(*) INTO v_contador FROM :TEMP_DISTINTO_MEDIADOR;
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'REGISTROS CON DISTINTO MEDIADOR: ' || v_contador,v_proc_name,io_contador);
	
	
		
	-- CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ACTUALIZACIÓN . REGISTROS MODIFICADOS ' || ::ROWCOUNT,v_proc_name,io_contador);
	
	
	--------------------------------------------------------------------------------------------------
	---------------------          RESUMEN -----------------------------------------------------------
	--------------------------------------------------------------------------------------------------
	-- --TIPOS_CASOS_CARTERA
	-- SELECT 'TEMP_CARTERA',* FROM :TEMP_CARTERA;
	-- --CASO1: PÓLIZA NO EXISTE EN RELASUJE
	-- SELECT 'TEMP_NO_EXISTE_RELASUJE',* FROM :TEMP_NO_EXISTE_RELASUJE;
	-- --CASO2: MEDIADOR NULL EN RELASUJE
	-- SELECT 'TEMP_MEDIADOR_NULL_RELASUJE',* FROM :TEMP_MEDIADOR_NULL_RELASUJE;
	-- --CASO3: COINCIDE MEDIADOR
	-- SELECT 'TEMP_COINCIDE_MEDIADOR',* FROM :TEMP_COINCIDE_MEDIADOR;
	-- --CASO4: DISTINTA SUBCLAVE
	-- SELECT 'TEMP_DISTINTA_SUBCLAVE',* FROM :TEMP_DISTINTA_SUBCLAVE;
	-- --CASO5: VARIOS MEDIADORES EN RELASUJE
	-- SELECT 'TEMP_VARIOS_MEDIADORES_RELASUJE',* FROM :TEMP_VARIOS_MEDIADORES_RELASUJE;
	-- --CASO6: DISTINTO MEDIADOR
	-- SELECT 'TEMP_DISTINTO_MEDIADOR',* FROM :TEMP_DISTINTO_MEDIADOR;
	--------------------------------------------------------------------------------------------------
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN RESUMEN',v_proc_name,io_contador);
	
	
	-- TEMP_CARTERA_EXCEL = SELECT C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA
	-- 	,C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE MEDIADOR
	-- 	, LPAD(C.IDMODALIDAD,3,0) MODALIDAD_CARTERA
	-- 	, CASE 
	-- 		WHEN R.NUM_POLIZA IS NULL THEN 'NO'
	-- 		ELSE 'SI'
	-- 	END EN_RELASUJE
	-- 	,R.POSITIONNAME,LPAD(R.MOD,3,0) MODALIDAD_RELASUJE
	-- 	, CASE
	-- 		WHEN  R.NUM_POLIZA IS NULL THEN '-'
	-- 		ELSE CASE
	-- 			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'SI'
	-- 			ELSE 'NO'
	-- 			END
	-- 	END MISMO_MEDIADOR
	-- 	, CASE	
	-- 		WHEN  R.NUM_POLIZA IS NULL THEN 'PÓLIZA NO EXISTE EN RELASUJE'
	-- 		ELSE CASE
	-- 			WHEN R.POSITIONNAME IS NULL THEN 'MEDIADOR NULL EN RELASUJE'
	-- 			WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE = R.POSITIONNAME THEN 'COINCIDE MEDIADOR'
	-- 			WHEN C.COD_MEDIADOR = SUBSTRING(R.POSITIONNAME,1,4) AND C.COD_SUBCLAVE != SUBSTRING(R.POSITIONNAME,5,9) THEN 'DISTINTA SUBCLAVE'
	-- 			WHEN (SELECT COUNT(*) FROM EXT.RELASUJE RJ WHERE RJ.NUM_POLIZA = C.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(RJ.MOD,3,0)) > 1 THEN 'VARIOS MEDIADORES EN RELASUJE'
	-- 			ELSE 'DISTINTO MEDIADOR'
	-- 		END
	-- 	END TIPO_CASO
	-- 	-- , C.MODIF_USER
	-- 	-- , CASE
	-- 	-- 		WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 	-- 		ELSE '-'
	-- 	-- 	END MODIFICADO
	-- 	, CASE
	-- 			-- WHEN (C.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 			WHEN EXISTS(SELECT 1 FROM EXT.CARTERA CR WHERE CR.ACTIVO > 0 AND CR.NUM_POLIZA = C.NUM_POLIZA AND CR.MODIF_USER != 'CDL') THEN 'MANUAL'
	-- 			ELSE '-'
	-- 		END MODIFICADO
	-- 		,COALESCE(R.FEC_INI,'1990-12-31') FECHA_INICIO
	-- 		,COALESCE(R.FEC_FIN,'2200-01-01') FECHA_FIN
	-- 		,C.FECHA_EFECTO
	-- 		,C.FECHA_VENCIMIENTO
	-- 	FROM EXT.CARTERA C 
	-- 	LEFT JOIN EXT.RELASUJE R ON C.NUM_POLIZA = R.NUM_POLIZA AND LPAD(C.IDMODALIDAD,3,0) = LPAD(R.MOD,3,0)
	-- 	LEFT JOIN (SELECT *
	-- 					,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
	-- 				FROM EXT.CARTERA CR 
	-- 				WHERE  ACTIVO > 0
	-- 				--AND CR.NUM_POLIZA = V_NUM_POLIZA
	-- 				) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND CRT.COD_MEDIADOR = C.COD_MEDIADOR AND CRT.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRT.RN = 1
	-- 	LEFT JOIN (SELECT * FROM EXT.CARTERA CR WHERE CR.RAMO = 'CAUCION' AND CR.NUM_FIANZA IS NOT NULL) CRTC ON C.NUM_POLIZA = CRTC.NUM_POLIZA 
	-- 		AND CRTC.COD_MEDIADOR = C.COD_MEDIADOR AND CRTC.COD_SUBCLAVE = C.COD_SUBCLAVE AND CRTC.NUM_FIANZA = C.NUM_FIANZA
	-- 	WHERE C.ACTIVO > 0
	-- 	-- AND CRTC.NUM_FIANZA IS NOT NULL
	-- 	-- FILTRO RAMO
	-- 	AND 1 = (CASE 
	-- 		WHEN C.RAMO = 'CREDITO' AND CRT.RN=1 THEN 1
	-- 		WHEN C.RAMO = 'CAUCION' THEN 1
	-- 		ELSE 0
	-- 	END)
	-- 	-- FILTRO EXISTEN EN RELASUJE
	-- 	-- AND 1 = (CASE 
	-- 	-- 			WHEN R.NUM_POLIZA IS NOT NULL THEN 1
	-- 	-- 			ELSE 0
	-- 	-- 		END
	-- 	-- )
	-- 	--FILTRO DISTINTOS MEDIADORES
	-- 	-- AND 1 = (CASE
	-- 	-- 		WHEN C.COD_MEDIADOR||'-'||C.COD_SUBCLAVE <> COALESCE(R.POSITIONNAME,'') THEN 1
	-- 	-- 		ELSE 0
	-- 	-- 		END
	-- 	-- )
		
	-- 	GROUP BY C.RAMO,C.ACTIVO,C.NUM_POLIZA,C.NUM_ANUALIDAD,C.NUM_FIANZA,C.COD_MEDIADOR,C.COD_SUBCLAVE,R.POSITIONNAME,LPAD(C.IDMODALIDAD,3,0),LPAD(R.MOD,3,0),R.NUM_POLIZA
	-- 	,R.FEC_INI,R.FEC_FIN,C.FECHA_EFECTO,C.FECHA_VENCIMIENTO
	-- 	ORDER BY NUM_POLIZA;
		
		
		
	-- 	-- C_MOTIVOS_ERROR_CREDITO = SELECT ROW_NUMBER() OVER () AS NUM_FILA,* FROM EXT.GET_POLIZAS_CREDITO_ERROR();
		
		
	-- 	-- SELECT 'C_MOTIVOS_ERROR_CREDITO',* FROM :C_MOTIVOS_ERROR_CREDITO;
	-- 	-- PRD
	-- 	-- C_MOTIVOS_ERROR_CREDITO = SELECT ROW_NUMBER() OVER () AS NUM_FILA,* FROM EXT.GET_POLIZAS_CREDITO_ERROR();
	-- 	-- v_totalFilas = RECORD_COUNT(:C_MOTIVOS_ERROR_CREDITO);
		
	-- 	-- FOR v_contFilas IN 1 .. v_totalFilas DO
	-- 	-- 	SELECT MOTIVO,NUM_POLIZA,ANUALIDAD,SUBSTRING(IDMEDIADOR,1,4),SUBSTRING(IDMEDIADOR,6,4),FECHA_VENCIMIENTO,FECHA_EFECTO,BATCHNAME 
	-- 	-- 		INTO v_tipoError,v_numPoliza,v_numAnualidad,v_codMediador,v_codSubclave,v_fechaVencimiento,v_fechaEfecto,v_batchname 
	-- 	-- 	FROM :C_MOTIVOS_ERROR_CREDITO 
	-- 	-- 	WHERE NUM_FILA = v_contFilas;
			
	-- 	-- 	IF v_tipoError = 'MEDIADOR DISTINTO EN CARTERA' THEN
	-- 	-- 		IF(SELECT COD_MEDIADOR FROM EXT.CARTERA WHERE NUM_POLIZA = v_numPoliza AND NUM_ANUALIDAD = v_numAnualidad AND ACTIVO = 1) = v_codMediador THEN
					
	-- 	-- 			CALL EXT.LIB_GLOBAL_CESCE:w_debug (v_idtenant, 'POLIZA : ' || v_numPoliza || ' ANUALIDAD ' || v_numAnualidad ||' con MEDIADOR ' || v_codMediador || ' SE MODIFICA POR TENER SUBCLAVE DISTINTA' , v_proc_name, v_idproceso);
					
	-- 	-- 			UPDATE EXT.CARTERA SET COD_SUBCLAVE = v_codSubclave, MODIF_USER = 'MANUAL SP_CORREGIR_POLIZAS', MODIF_DATE = CURRENT_TIMESTAMP
	-- 	-- 				WHERE NUM_POLIZA = v_numPoliza AND NUM_ANUALIDAD = v_numAnualidad AND COD_MEDIADOR = v_codMediador AND RAMO = 'CREDITO' AND ACTIVO = 1;
	-- 	-- 		END IF;
	-- 	-- 	END IF;	
			
	-- 	-- 	IF v_tipoError = 'FECHA VENCIMIENTO DISTINTA EN CARTERA' THEN
	-- 	-- 		UPDATE EXT.CARTERA SET FECHA_VENCIMIENTO = :v_fechaVencimiento, MODIF_USER = 'MANUAL SP_CORREGIR_POLIZAS', MODIF_DATE = CURRENT_TIMESTAMP
	-- 	-- 				WHERE NUM_POLIZA = :v_numPoliza AND NUM_ANUALIDAD = :v_numAnualidad AND COD_MEDIADOR = :v_codMediador AND RAMO = 'CREDITO' AND ACTIVO = 1;
	-- 	-- 	END IF;
			
	-- 	-- 	IF v_tipoError = 'FECHA EFECTO DISTINTA EN CARTERA' THEN
	-- 	-- 		UPDATE EXT.CARTERA SET FECHA_EFECTO = :v_fechaEfecto, MODIF_USER = 'MANUAL SP_CORREGIR_POLIZAS', MODIF_DATE = CURRENT_TIMESTAMP
	-- 	-- 				WHERE NUM_POLIZA = :v_numPoliza AND NUM_ANUALIDAD = :v_numAnualidad AND COD_MEDIADOR = :v_codMediador AND RAMO = 'CREDITO' AND ACTIVO = 1;
	-- 	-- 	END IF;
	-- 	-- END FOR;
		
	-- 	-- SELECT DISTINCT TIPO_CASO FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CREDITO' AND ACTIVO > 0;
		
	-- 	SELECT 'EXCEL_CREDITO',* FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CREDITO' AND ACTIVO > 0
	-- 	AND TIPO_CASO NOT IN ('COINCIDE MEDIADOR')
	-- 	;
	-- 	-- SELECT DISTINCT TIPO_CASO FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CAUCION' AND ACTIVO > 0;
	-- 	SELECT 'EXCEL_CAUCION',* FROM :TEMP_CARTERA_EXCEL WHERE RAMO = 'CAUCION' AND ACTIVO > 0
	-- 	AND TIPO_CASO NOT IN ('COINCIDE MEDIADOR');
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'ELIMINAMOS DUPLICADOS. PROCEDIMIENTO SP_CORREGIR_POLIZAS_DUPLICADAS_PRD',v_proc_name,io_contador);
	--PROCEDIMIENTO ELIMINAR DUPLICADOS
	CALL EXT.SP_CORREGIR_POLIZAS_DUPLICADAS_PRD();
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN ELIMINAR DUPLICADOS. PROCEDIMIENTO SP_CORREGIR_POLIZAS_DUPLICADAS_PRD',v_proc_name,io_contador);
	
	
		
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN PROCEDIMIENTO',v_proc_name,io_contador);
END