CREATE OR REPLACE PROCEDURE EXT.SP_CORREGIR_POLIZAS_DUPLICADAS_PRD()
LANGUAGE SQLSCRIPT SQL SECURITY INVOKER DEFAULT SCHEMA EXT AS

BEGIN
	--DECLARACIÓN DE VARIABLES
	DECLARE V_CONT_TOTAL INT = 0;
	DECLARE V_CONT_TOTAL_FINAL INT = 0;
	DECLARE V_FILA_CONT INT = 0;
	DECLARE V_NUM_POLIZA BIGINT;
	DECLARE V_NUM_FIANZA BIGINT;
	DECLARE V_NUM_AVAL_HOST BIGINT;
	DECLARE V_NUM_ANUALIDAD INT;
	DECLARE V_COD_MEDIADOR VARCHAR(4);
	DECLARE V_COD_SUBCLAVE VARCHAR(4);
	DECLARE i_Tenant VARCHAR(127);
	DECLARE cVersion CONSTANT VARCHAR(2) := '01';
	DECLARE v_proc_name VARCHAR2(50) := ::CURRENT_OBJECT_NAME;
	DECLARE io_contador Number := 0;


	--CONTROLADOR DE EXCEPCIONES
    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN	
	    CALL LIB_GLOBAL_CESCE :w_debug (
	            i_Tenant,
	            v_proc_name || '. SQL ERROR_MESSAGE: ' || IFNULL( ::SQL_ERROR_MESSAGE, '') || '. SQL_ERROR_CODE: ' ||  ::SQL_ERROR_CODE,
	            v_proc_name,
	            io_contador
	        );
        -- RESIGNAL;
    END;
	
	--OBTENER TENANT
	SELECT TENANTID INTO i_Tenant FROM CS_TENANT;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'STARTING with SESSION_USER: ' || SESSION_USER || ' version ' || cVersion,v_proc_name,io_contador);
	
	
	-----------------------------------------------------------------
	-------------------------- CAUCION ------------------------------
	-----------------------------------------------------------------
		--OBTENER REGISTROS TOTALES
		SELECT COUNT(*) INTO V_CONT_TOTAL
		FROM (
		SELECT 1
		FROM EXT.CARTERA
		WHERE RAMO = 'CAUCION'
		AND ACTIVO = 1
		GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		HAVING COUNT(*) > 1
		) X;

		CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS A TRATAR EN CAUCIÓN: ' || V_CONT_TOTAL,v_proc_name,io_contador);
		
		--TABLA TEMPORAL
		TEMP_CAUCION = SELECT NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,RAMO,COUNT(*)
				FROM EXT.CARTERA
				WHERE RAMO = 'CAUCION'
				AND ACTIVO = 1
				AND NUM_FIANZA IS NOT NULL
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,RAMO
				HAVING COUNT(*) > 1
				ORDER BY NUM_POLIZA,NUM_FIANZA;


				
				UPDATE  C
				SET ACTIVO = 0,
				MODIF_USER = MODIF_USER || ' - DPLCD',
				MODIF_DATE = CURRENT_TIMESTAMP
				FROM EXT.CARTERA C
				WHERE (NUM_POLIZA, NUM_FIANZA, MODIF_SOURCE,CREATEDATE,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (
		    		SELECT NUM_POLIZA, NUM_FIANZA, MODIF_SOURCE,CREATEDATE,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		    		FROM (
		    	    	SELECT 
		    	        	CART.NUM_POLIZA,
		    	        	CART.NUM_FIANZA,
		    	        	CART.MODIF_SOURCE,
		    	        	CART.CREATEDATE,
		    	        	CART.NUM_AVAL_HOST,
		    	        	CART.COD_MEDIADOR,
		    	        	CART.COD_SUBCLAVE,
		    	        	ROW_NUMBER() OVER (
		    	            	PARTITION BY CART.NUM_POLIZA, CART.COD_MEDIADOR, CART.COD_SUBCLAVE, CART.NUM_FIANZA, CART.NUM_AVAL_HOST,CART.COD_MEDIADOR,CART.COD_SUBCLAVE
		    	            	ORDER BY MODIF_DATE DESC
		    	        	) AS RN
		    	    	FROM EXT.CARTERA CART
		    	    	INNER JOIN :TEMP_CAUCION AS TMP
				            ON CART.NUM_POLIZA   = TMP.NUM_POLIZA
				          AND CART.NUM_FIANZA   = TMP.NUM_FIANZA
				          AND CART.NUM_AVAL_HOST= TMP.NUM_AVAL_HOST
				          AND CART.COD_MEDIADOR = TMP.COD_MEDIADOR
				          AND CART.COD_SUBCLAVE = TMP.COD_SUBCLAVE
		    	    	WHERE CART.ACTIVO = 1
		    	    		AND CART.NUM_FIANZA IS NOT NULL
		    		)
		    		WHERE RN >= 2
				);
				
	-- SELECT '***',NUM_POLIZA, NUM_FIANZA, MODIF_SOURCE,CREATEDATE,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
	-- 	    		FROM (
		    	    	
			
			SELECT COUNT(*) INTO V_CONT_TOTAL_FINAL
			FROM (
				SELECT 1
				FROM EXT.CARTERA
				WHERE RAMO = 'CAUCION'
				AND ACTIVO = 1
				AND NUM_FIANZA IS NOT NULL
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				HAVING COUNT(*) > 1
			) X;
		
			CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS CORREGIDAS EN CAUCIÓN '|| V_CONT_TOTAL - V_CONT_TOTAL_FINAL,v_proc_name,io_contador);
			
		--TABLA TEMPORAL_EXPEDIENTES
		TEMP_CAUCION_EXPEDIENTES = SELECT NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,RAMO,COUNT(*)
				FROM EXT.CARTERA
				WHERE RAMO = 'CAUCION'
				AND ACTIVO = 1
				AND NUM_FIANZA IS NULL
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,RAMO
				HAVING COUNT(*) > 1
				ORDER BY NUM_POLIZA,NUM_FIANZA;


				
				UPDATE  C
				SET ACTIVO = 0,
				MODIF_USER = MODIF_USER || ' - DPLCD',
				MODIF_DATE = CURRENT_TIMESTAMP
				FROM EXT.CARTERA C
				WHERE (NUM_POLIZA, COALESCE(NUM_FIANZA,-1), COALESCE(MODIF_SOURCE,''),CREATEDATE,COALESCE(NUM_AVAL_HOST,-1),COD_MEDIADOR,COD_SUBCLAVE) IN (
		    		SELECT NUM_POLIZA, COALESCE(NUM_FIANZA,-1) NUM_FIANZA, COALESCE(MODIF_SOURCE,'') MODIF_SOURCE,CREATEDATE,COALESCE(NUM_AVAL_HOST,-1) NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		    		FROM (
		    	    	SELECT 
		    	        	CART.NUM_POLIZA,
		    	        	CART.NUM_FIANZA,
		    	        	CART.MODIF_SOURCE,
		    	        	CART.CREATEDATE,
		    	        	CART.NUM_AVAL_HOST,
		    	        	CART.COD_MEDIADOR,
		    	        	CART.COD_SUBCLAVE,
		    	        	ROW_NUMBER() OVER (
		    	            	PARTITION BY CART.NUM_POLIZA, CART.COD_MEDIADOR, CART.COD_SUBCLAVE, CART.NUM_FIANZA, CART.NUM_AVAL_HOST,CART.COD_MEDIADOR,CART.COD_SUBCLAVE
		    	            	ORDER BY MODIF_DATE DESC
		    	        	) AS RN
		    	    	FROM EXT.CARTERA CART
		    	    	INNER JOIN :TEMP_CAUCION_EXPEDIENTES AS TMP
				            ON CART.NUM_POLIZA   = TMP.NUM_POLIZA
				          AND COALESCE(CART.NUM_FIANZA,-1)   = COALESCE(TMP.NUM_FIANZA,-1)
				          AND COALESCE(CART.NUM_AVAL_HOST,-1)= COALESCE(TMP.NUM_AVAL_HOST,-1)
				          AND CART.COD_MEDIADOR = TMP.COD_MEDIADOR
				          AND CART.COD_SUBCLAVE = TMP.COD_SUBCLAVE
		    	    	WHERE CART.ACTIVO = 1
		    	    		AND COALESCE(CART.NUM_FIANZA,-1) = -1
		    		)
		    		WHERE RN >= 2
				);
				

			
			SELECT COUNT(*) INTO V_CONT_TOTAL_FINAL
			FROM (
				SELECT 1
				FROM EXT.CARTERA
				WHERE RAMO = 'CAUCION'
				AND ACTIVO = 1
				AND NUM_FIANZA IS NULL
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				HAVING COUNT(*) > 1
			) X;
		
			CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'EXPEDIENTES CORREGIDOS EN CAUCIÓN '|| V_CONT_TOTAL - V_CONT_TOTAL_FINAL,v_proc_name,io_contador);
	-----------------------------------------------------------------
	---------------------- CREDITO ----------------------------------
	-----------------------------------------------------------------
	

		V_CONT_TOTAL = 0;
		
		--OBTENER REGISTROS TOTALES
		SELECT COUNT(*) INTO V_CONT_TOTAL
		FROM (
			SELECT 1
			FROM EXT.CARTERA
			WHERE RAMO = 'CREDITO'
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
		) X;
	

	--TABLA TEMPORAL
	TEMP_CREDITO = SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE,COUNT(*)
			FROM EXT.CARTERA
			WHERE RAMO = 'CREDITO'
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
		
		
			UPDATE  C
				SET ACTIVO = 0,
				MODIF_USER = MODIF_USER || ' - DPLCD',
				MODIF_DATE = CURRENT_TIMESTAMP
				FROM EXT.CARTERA C
				WHERE (NUM_POLIZA, NUM_ANUALIDAD, MODIF_SOURCE,CREATEDATE,COD_MEDIADOR,COD_SUBCLAVE) IN (
		    		SELECT NUM_POLIZA, NUM_ANUALIDAD, MODIF_SOURCE,CREATEDATE,COD_MEDIADOR,COD_SUBCLAVE
		    		FROM (
		    		    SELECT 
		    		        CART.NUM_POLIZA,
		    		        CART.NUM_ANUALIDAD,
		    		        CART.MODIF_SOURCE,
		    		        CART.CREATEDATE,
		    		        CART.COD_MEDIADOR,
		    		        CART.COD_SUBCLAVE,
		    		        ROW_NUMBER() OVER (
		    		            PARTITION BY CART.NUM_POLIZA, CART.COD_MEDIADOR, CART.COD_SUBCLAVE, CART.NUM_ANUALIDAD
		    		            ORDER BY MODIF_DATE DESC
		    		        ) AS RN
		    		    FROM EXT.CARTERA CART
		    		    INNER JOIN :TEMP_CREDITO AS TMP
        					 ON CART.NUM_POLIZA   = TMP.NUM_POLIZA
        					AND CART.NUM_ANUALIDAD   = TMP.NUM_ANUALIDAD
        					AND CART.COD_MEDIADOR = TMP.COD_MEDIADOR
        					AND CART.COD_SUBCLAVE = TMP.COD_SUBCLAVE
		    		    WHERE CART.ACTIVO = 1
		    		)
		    		WHERE RN >= 2
				);
				
		
		
		SELECT COUNT(*) INTO V_CONT_TOTAL_FINAL
		FROM (
			SELECT 1
			FROM EXT.CARTERA
			WHERE RAMO = 'CREDITO'
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
		) X;
		
		CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS CORREGIDAS EN CRÉDITO '|| V_CONT_TOTAL - V_CONT_TOTAL_FINAL,v_proc_name,io_contador);
	
		


CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN PROCEDIMIENTO',v_proc_name,io_contador);

END;