CREATE OR REPLACE PROCEDURE EXT.SP_CORREGIR_POLIZAS_DUPLICADAS(IN i_tipo_ejecucion INT --0: INICIO ; 1: FINAL
	, IN i_ramo VARCHAR(10))
LANGUAGE SQLSCRIPT SQL SECURITY INVOKER DEFAULT SCHEMA EXT AS

BEGIN
	--DECLARACIÓN DE VARIABLES
	DECLARE V_CONT_TOTAL INT = 0;
	DECLARE V_CONT_TOTAL_FINAL INT = 0;
	DECLARE V_FILA_CONT INT = 0;
	DECLARE V_NUM_POLIZA BIGINT;
	DECLARE V_NUM_FIANZA BIGINT;
	DECLARE V_NUM_AVAL_HOST BIGINT;
	DECLARE V_NUM_ANUALIDAD INT;
	DECLARE V_COD_MEDIADOR VARCHAR(4);
	DECLARE V_COD_SUBCLAVE VARCHAR(4);
	DECLARE i_Tenant VARCHAR(127);
	DECLARE cVersion CONSTANT VARCHAR(2) := '01';
	DECLARE v_proc_name VARCHAR2(50) := ::CURRENT_OBJECT_NAME;
	DECLARE io_contador Number := 0;


	--CONTROLADOR DE EXCEPCIONES
    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN	
	    CALL LIB_GLOBAL_CESCE :w_debug (
	            i_Tenant,
	            v_proc_name || '. SQL ERROR_MESSAGE: ' || IFNULL( ::SQL_ERROR_MESSAGE, '') || '. SQL_ERROR_CODE: ' ||  ::SQL_ERROR_CODE,
	            v_proc_name,
	            io_contador
	        );
        -- RESIGNAL;
    END;
	
	--OBTENER TENANT
	SELECT TENANTID INTO i_Tenant FROM CS_TENANT;
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'STARTING with SESSION_USER: ' || SESSION_USER || ' version ' || cVersion,v_proc_name,io_contador);
	
	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'CREACIÓN TABLAS BACKUP',v_proc_name,io_contador);
	--CREACIÓN DE TABLAS DE BKP PARA PRUEBAS
	IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= ::CURRENT_OBJECT_SCHEMA and TABLE_NAME = 'CARTERA_BKP_SMM') IS NULL THEN
        CREATE COLUMN TABLE EXT.CARTERA_BKP_SMM AS (SELECT * FROM EXT.CARTERA WHERE 1=0);
	END IF;

	IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= ::CURRENT_OBJECT_SCHEMA and TABLE_NAME = 'CARTERA_BKP_TEST_SMM') IS NULL THEN
        CREATE COLUMN TABLE "EXT"."CARTERA_BKP_TEST_SMM"(
			"TIPO" VARCHAR(10),
			"RAMO" VARCHAR(20) NOT NULL,
			"IDPRODUCT" NVARCHAR(127) NOT NULL,
			"NUM_POLIZA" BIGINT CS_FIXED NOT NULL,
			"IDMODALIDAD" SMALLINT CS_INT NOT NULL,
			"IDSUBMODALIDAD" VARCHAR(20),
			"NUM_FIANZA" DECIMAL(30) CS_FIXED,
			"NUM_EXPEDIENTE" BIGINT CS_FIXED DEFAULT 0,
			"NUM_AVAL_HOST" BIGINT CS_FIXED,
			"NUM_ANUALIDAD" INTEGER CS_INT NOT NULL,
			"FECHA_EMISION" DATE CS_DAYDATE,
			"FECHA_EFECTO" DATE CS_DAYDATE,
			"FECHA_VENCIMIENTO" DATE CS_DAYDATE,
			"IDPAIS" SMALLINT CS_INT,
			"PRIMA_PROVISIONAL_INT" DECIMAL(18, 3) CS_FIXED,
			"PRIMA_PROVISIONAL_EXT" DECIMAL(18, 3) CS_FIXED,
			"IDDIVISA_INT" SMALLINT CS_INT,
			"IDDIVISA_EXT" SMALLINT CS_INT,
			"IDDIVISA_COBERTURA" SMALLINT CS_INT,
			"PRIMA_MIN_INT" DECIMAL(18, 3) CS_FIXED,
			"PRIMA_MIN_EXT" DECIMAL(18, 3) CS_FIXED,
			"COD_MEDIADOR" NVARCHAR(10),
			"COD_SUBCLAVE" NVARCHAR(10),
			"P_INTERMEDIACION" DECIMAL(6, 3) CS_FIXED,
			"FECHA_INICIO" DATE CS_DAYDATE NOT NULL,
			"FECHA_FIN" DATE CS_DAYDATE,
			"P_ESPECIAL_EMISION" DECIMAL(6, 4) CS_FIXED,
			"P_ESPECIAL_RENOVACION" DECIMAL(6, 4) CS_FIXED,
			"NIF_TOMADOR" NVARCHAR(20),
			"NOMBRE_TOMADOR" NVARCHAR(50),
			"FECHA_EFECTO_TRASPASO" DATE CS_DAYDATE,
			"MEDIADOR_PRINCIPAL_CIC" TINYINT CS_INT,
			"ACTIVO" TINYINT CS_INT DEFAULT 1,
			"CREATEDATE" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
			"MODIF_DATE" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
			"MODIF_USER" VARCHAR(50),
			"MODIF_SOURCE" VARCHAR(100),
			"FECHA_INICIO_OPESP" DATE CS_DAYDATE,
			"FECHA_FIN_OPESP" DATE CS_DAYDATE
		);
	END IF;


	--COPIA DE LA TABLA CARTERA A BKP
	TRUNCATE TABLE EXT.CARTERA_BKP_SMM;
	TRUNCATE TABLE EXT.CARTERA_BKP_TEST_SMM;
	INSERT INTO EXT.CARTERA_BKP_SMM SELECT * FROM EXT.CARTERA WHERE RAMO = :i_ramo;

	CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PARAMETROS i_ramo: ' || :i_ramo || ' TIPO EJECUCIÓN i_tipo_ejecucion: ' || CASE WHEN i_tipo_ejecucion = 0 THEN 'INICIAL' ELSE 'FINAL' END,v_proc_name,io_contador);
	
	IF :i_ramo = 'CAUCION' THEN

		--OBTENER REGISTROS TOTALES
		SELECT COUNT(*) INTO V_CONT_TOTAL
		FROM (
		SELECT 1
		FROM EXT.CARTERA_BKP_SMM
		WHERE RAMO = :i_ramo
		--AND MODIF_USER = 'CDL'
		AND ACTIVO = 1
		GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		HAVING COUNT(*) > 1
		) X;

		CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS A TRATAR EN CAUCIÓN: ' || V_CONT_TOTAL,v_proc_name,io_contador);
		
		--TABLA TEMPORAL
		TEMP_CAUCION = SELECT ROW_NUMBER() OVER () AS NUM_FILA,* 
			FROM (
				SELECT NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
					,COUNT(*)
				FROM EXT.CARTERA_BKP_SMM
				WHERE RAMO = :i_ramo
				AND ACTIVO = 1
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				HAVING COUNT(*) > 1
				ORDER BY NUM_POLIZA,NUM_FIANZA
			);


		IF :i_tipo_ejecucion = 0 THEN
			INSERT INTO EXT.CARTERA_BKP_TEST_SMM(
				TIPO,
				RAMO,
				IDPRODUCT,
				NUM_POLIZA,
				IDMODALIDAD,
				IDSUBMODALIDAD,
				NUM_FIANZA,
				NUM_EXPEDIENTE,
				NUM_AVAL_HOST,
				NUM_ANUALIDAD,
				FECHA_EMISION,
				FECHA_EFECTO,
				FECHA_VENCIMIENTO,
				IDPAIS,
				PRIMA_PROVISIONAL_INT,
				PRIMA_PROVISIONAL_EXT,
				IDDIVISA_INT,
				IDDIVISA_EXT,
				IDDIVISA_COBERTURA,
				PRIMA_MIN_INT,
				PRIMA_MIN_EXT,
				COD_MEDIADOR,
				COD_SUBCLAVE,
				P_INTERMEDIACION,
				FECHA_INICIO,
				FECHA_FIN,
				P_ESPECIAL_EMISION,
				P_ESPECIAL_RENOVACION,
				NIF_TOMADOR,
				NOMBRE_TOMADOR,
				FECHA_EFECTO_TRASPASO,
				MEDIADOR_PRINCIPAL_CIC,
				ACTIVO,
				CREATEDATE,
				MODIF_DATE,
				MODIF_USER,
				MODIF_SOURCE,
				FECHA_INICIO_OPESP,
				FECHA_FIN_OPESP)
			SELECT 'INICIO',
				RAMO,
				IDPRODUCT,
				NUM_POLIZA,
				IDMODALIDAD,
				IDSUBMODALIDAD,
				NUM_FIANZA,
				NUM_EXPEDIENTE,
				NUM_AVAL_HOST,
				NUM_ANUALIDAD,
				FECHA_EMISION,
				FECHA_EFECTO,
				FECHA_VENCIMIENTO,
				IDPAIS,
				PRIMA_PROVISIONAL_INT,
				PRIMA_PROVISIONAL_EXT,
				IDDIVISA_INT,
				IDDIVISA_EXT,
				IDDIVISA_COBERTURA,
				PRIMA_MIN_INT,
				PRIMA_MIN_EXT,
				COD_MEDIADOR,
				COD_SUBCLAVE,
				P_INTERMEDIACION,
				FECHA_INICIO,
				FECHA_FIN,
				P_ESPECIAL_EMISION,
				P_ESPECIAL_RENOVACION,
				NIF_TOMADOR,
				NOMBRE_TOMADOR,
				FECHA_EFECTO_TRASPASO,
				MEDIADOR_PRINCIPAL_CIC,
				ACTIVO,
				CREATEDATE,
				MODIF_DATE,
				MODIF_USER,
				MODIF_SOURCE,
				FECHA_INICIO_OPESP,
				FECHA_FIN_OPESP
			FROM EXT.CARTERA_BKP_SMM
			WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CAUCION)
			AND ACTIVO = 1
			ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
		ELSE 

			FOR V_FILA_CONT IN 1 .. V_CONT_TOTAL DO
			BEGIN
				SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				INTO V_NUM_POLIZA, V_NUM_FIANZA, V_NUM_AVAL_HOST,V_COD_MEDIADOR,V_COD_SUBCLAVE
				FROM :TEMP_CAUCION 
				WHERE NUM_FILA = V_FILA_CONT;
			
		
				DELETE FROM EXT.CARTERA_BKP_SMM
				WHERE (NUM_POLIZA, NUM_FIANZA, MODIF_SOURCE,CREATEDATE,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (
		    		SELECT NUM_POLIZA, NUM_FIANZA, MODIF_SOURCE,CREATEDATE,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		    		FROM (
		    	    	SELECT 
		    	        	NUM_POLIZA,
		    	        	NUM_FIANZA,
		    	        	MODIF_SOURCE,
		    	        	CREATEDATE,
		    	        	NUM_AVAL_HOST,
		    	        	COD_MEDIADOR,
		    	        	COD_SUBCLAVE,
		    	        	ROW_NUMBER() OVER (
		    	            	PARTITION BY NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, NUM_FIANZA, NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
		    	            	ORDER BY MODIF_DATE DESC
		    	        	) AS RN
		    	    	FROM EXT.CARTERA_BKP_SMM
		    	    	WHERE NUM_POLIZA = :V_NUM_POLIZA
		    	    		AND NUM_FIANZA = :V_NUM_FIANZA
		    	    		AND NUM_AVAL_HOST = :V_NUM_AVAL_HOST
		    	    		AND COD_MEDIADOR = :V_COD_MEDIADOR
		    	    		AND COD_SUBCLAVE = :V_COD_SUBCLAVE
		    	    		AND ACTIVO = 1
		    	    		AND NUM_FIANZA IS NOT NULL
		    		)
		    		WHERE RN >= 2
				);
			END;
			END FOR;
	
			INSERT INTO EXT.CARTERA_BKP_TEST_SMM(
				TIPO,
				RAMO,
				IDPRODUCT,
				NUM_POLIZA,
				IDMODALIDAD,
				IDSUBMODALIDAD,
				NUM_FIANZA,
				NUM_EXPEDIENTE,
				NUM_AVAL_HOST,
				NUM_ANUALIDAD,
				FECHA_EMISION,
				FECHA_EFECTO,
				FECHA_VENCIMIENTO,
				IDPAIS,
				PRIMA_PROVISIONAL_INT,
				PRIMA_PROVISIONAL_EXT,
				IDDIVISA_INT,
				IDDIVISA_EXT,
				IDDIVISA_COBERTURA,
				PRIMA_MIN_INT,
				PRIMA_MIN_EXT,
				COD_MEDIADOR,
				COD_SUBCLAVE,
				P_INTERMEDIACION,
				FECHA_INICIO,
				FECHA_FIN,
				P_ESPECIAL_EMISION,
				P_ESPECIAL_RENOVACION,
				NIF_TOMADOR,
				NOMBRE_TOMADOR,
				FECHA_EFECTO_TRASPASO,
				MEDIADOR_PRINCIPAL_CIC,
				ACTIVO,
				CREATEDATE,
				MODIF_DATE,
				MODIF_USER,
				MODIF_SOURCE,
				FECHA_INICIO_OPESP,
				FECHA_FIN_OPESP)
			SELECT 'FINAL',
				RAMO,
				IDPRODUCT,
				NUM_POLIZA,
				IDMODALIDAD,
				IDSUBMODALIDAD,
				NUM_FIANZA,
				NUM_EXPEDIENTE,
				NUM_AVAL_HOST,
				NUM_ANUALIDAD,
				FECHA_EMISION,
				FECHA_EFECTO,
				FECHA_VENCIMIENTO,
				IDPAIS,
				PRIMA_PROVISIONAL_INT,
				PRIMA_PROVISIONAL_EXT,
				IDDIVISA_INT,
				IDDIVISA_EXT,
				IDDIVISA_COBERTURA,
				PRIMA_MIN_INT,
				PRIMA_MIN_EXT,
				COD_MEDIADOR,
				COD_SUBCLAVE,
				P_INTERMEDIACION,
				FECHA_INICIO,
				FECHA_FIN,
				P_ESPECIAL_EMISION,
				P_ESPECIAL_RENOVACION,
				NIF_TOMADOR,
				NOMBRE_TOMADOR,
				FECHA_EFECTO_TRASPASO,
				MEDIADOR_PRINCIPAL_CIC,
				ACTIVO,
				CREATEDATE,
				MODIF_DATE,
				MODIF_USER,
				MODIF_SOURCE,
				FECHA_INICIO_OPESP,
				FECHA_FIN_OPESP
			FROM EXT.CARTERA_BKP_SMM
			WHERE (NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CAUCION)
				AND ACTIVO = 1
			ORDER BY NUM_POLIZA,NUM_FIANZA,NUM_AVAL_HOST;
			
			SELECT COUNT(*) INTO V_CONT_TOTAL_FINAL
			FROM (
				SELECT 1
				FROM EXT.CARTERA_BKP_SMM
				WHERE RAMO = :i_ramo
				AND ACTIVO = 1
				GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_FIANZA,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE
				HAVING COUNT(*) > 1
			) X;
		
			CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS CORREGIDAS EN CAUCIÓN '|| V_CONT_TOTAL - V_CONT_TOTAL_FINAL,v_proc_name,io_contador);
			
		END IF;
	-- CREDITO
	ELSEIF :i_ramo = 'CREDITO' THEN

		V_CONT_TOTAL = 0;
		
		--OBTENER REGISTROS TOTALES
		SELECT COUNT(*) INTO V_CONT_TOTAL
		FROM (
			SELECT 1
			FROM EXT.CARTERA_BKP_SMM
			WHERE RAMO = :i_ramo
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
		) X;
	

	--TABLA TEMPORAL
	TEMP_CREDITO = SELECT ROW_NUMBER() OVER () AS NUM_FILA,* 
		FROM (
			SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
				,COUNT(*)
			FROM EXT.CARTERA_BKP_SMM
			WHERE RAMO = :i_ramo
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD
		);
		
		
		
	IF :i_tipo_ejecucion = 0 THEN
		INSERT INTO EXT.CARTERA_BKP_TEST_SMM(
			TIPO,
			RAMO,
			IDPRODUCT,
			NUM_POLIZA,
			IDMODALIDAD,
			IDSUBMODALIDAD,
			NUM_FIANZA,
			NUM_EXPEDIENTE,
			NUM_AVAL_HOST,
			NUM_ANUALIDAD,
			FECHA_EMISION,
			FECHA_EFECTO,
			FECHA_VENCIMIENTO,
			IDPAIS,
			PRIMA_PROVISIONAL_INT,
			PRIMA_PROVISIONAL_EXT,
			IDDIVISA_INT,
			IDDIVISA_EXT,
			IDDIVISA_COBERTURA,
			PRIMA_MIN_INT,
			PRIMA_MIN_EXT,
			COD_MEDIADOR,
			COD_SUBCLAVE,
			P_INTERMEDIACION,
			FECHA_INICIO,
			FECHA_FIN,
			P_ESPECIAL_EMISION,
			P_ESPECIAL_RENOVACION,
			NIF_TOMADOR,
			NOMBRE_TOMADOR,
			FECHA_EFECTO_TRASPASO,
			MEDIADOR_PRINCIPAL_CIC,
			ACTIVO,
			CREATEDATE,
			MODIF_DATE,
			MODIF_USER,
			MODIF_SOURCE,
			FECHA_INICIO_OPESP,
			FECHA_FIN_OPESP)
		SELECT 'INICIO',
			RAMO,
			IDPRODUCT,
			NUM_POLIZA,
			IDMODALIDAD,
			IDSUBMODALIDAD,
			NUM_FIANZA,
			NUM_EXPEDIENTE,
			NUM_AVAL_HOST,
			NUM_ANUALIDAD,
			FECHA_EMISION,
			FECHA_EFECTO,
			FECHA_VENCIMIENTO,
			IDPAIS,
			PRIMA_PROVISIONAL_INT,
			PRIMA_PROVISIONAL_EXT,
			IDDIVISA_INT,
			IDDIVISA_EXT,
			IDDIVISA_COBERTURA,
			PRIMA_MIN_INT,
			PRIMA_MIN_EXT,
			COD_MEDIADOR,
			COD_SUBCLAVE,
			P_INTERMEDIACION,
			FECHA_INICIO,
			FECHA_FIN,
			P_ESPECIAL_EMISION,
			P_ESPECIAL_RENOVACION,
			NIF_TOMADOR,
			NOMBRE_TOMADOR,
			FECHA_EFECTO_TRASPASO,
			MEDIADOR_PRINCIPAL_CIC,
			ACTIVO,
			CREATEDATE,
			MODIF_DATE,
			MODIF_USER,
			MODIF_SOURCE,
			FECHA_INICIO_OPESP,
			FECHA_FIN_OPESP
		FROM EXT.CARTERA_BKP_SMM
		WHERE (NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CREDITO)
			AND ACTIVO = 1
		ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
	ELSE 

		FOR V_FILA_CONT IN 1 .. V_CONT_TOTAL DO
		BEGIN
			DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    		BEGIN 
			    CALL LIB_GLOBAL_CESCE :w_debug (
			            i_Tenant,
			            v_proc_name || '. ERROR EN V_FILA_CONT ' || :V_FILA_CONT || ' --- ' || IFNULL( ::SQL_ERROR_MESSAGE, '') || '. SQL_ERROR_CODE: ' ||  ::SQL_ERROR_CODE,
			            v_proc_name,
			            io_contador
			        );
			        -- RESIGNAL;
			
			END;
			
			SELECT NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			INTO V_NUM_POLIZA, V_NUM_ANUALIDAD,V_COD_MEDIADOR,V_COD_SUBCLAVE
			FROM :TEMP_CREDITO 
			WHERE NUM_FILA = V_FILA_CONT;
		
		
			DELETE FROM EXT.CARTERA_BKP_SMM
			WHERE (NUM_POLIZA, NUM_ANUALIDAD, MODIF_SOURCE,CREATEDATE,COD_MEDIADOR,COD_SUBCLAVE) IN (
		    	SELECT NUM_POLIZA, NUM_ANUALIDAD, MODIF_SOURCE,CREATEDATE,COD_MEDIADOR,COD_SUBCLAVE
		    	FROM (
		    	    SELECT 
		    	        NUM_POLIZA,
		    	        NUM_ANUALIDAD,
		    	        MODIF_SOURCE,
		    	        CREATEDATE,
		    	        COD_MEDIADOR,
		    	        COD_SUBCLAVE,
		    	        ROW_NUMBER() OVER (
		    	            PARTITION BY NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, NUM_ANUALIDAD
		    	            ORDER BY MODIF_DATE DESC
		    	        ) AS RN
		    	    FROM EXT.CARTERA_BKP_SMM
		    	    WHERE NUM_POLIZA = :V_NUM_POLIZA
		    	      AND NUM_ANUALIDAD = :V_NUM_ANUALIDAD
		    	      AND COD_MEDIADOR = :V_COD_MEDIADOR
		    	      AND COD_SUBCLAVE = :V_COD_SUBCLAVE
		    	      AND ACTIVO = 1
		    	)
		    	WHERE RN >= 2
			);
			
			
			
		END;
		END FOR;
	
		INSERT INTO EXT.CARTERA_BKP_TEST_SMM(
			TIPO,
			RAMO,
			IDPRODUCT,
			NUM_POLIZA,
			IDMODALIDAD,
			IDSUBMODALIDAD,
			NUM_FIANZA,
			NUM_EXPEDIENTE,
			NUM_AVAL_HOST,
			NUM_ANUALIDAD,
			FECHA_EMISION,
			FECHA_EFECTO,
			FECHA_VENCIMIENTO,
			IDPAIS,
			PRIMA_PROVISIONAL_INT,
			PRIMA_PROVISIONAL_EXT,
			IDDIVISA_INT,
			IDDIVISA_EXT,
			IDDIVISA_COBERTURA,
			PRIMA_MIN_INT,
			PRIMA_MIN_EXT,
			COD_MEDIADOR,
			COD_SUBCLAVE,
			P_INTERMEDIACION,
			FECHA_INICIO,
			FECHA_FIN,
			P_ESPECIAL_EMISION,
			P_ESPECIAL_RENOVACION,
			NIF_TOMADOR,
			NOMBRE_TOMADOR,
			FECHA_EFECTO_TRASPASO,
			MEDIADOR_PRINCIPAL_CIC,
			ACTIVO,
			CREATEDATE,
			MODIF_DATE,
			MODIF_USER,
			MODIF_SOURCE,
			FECHA_INICIO_OPESP,
			FECHA_FIN_OPESP)
		SELECT 'FINAL',
			RAMO,
			IDPRODUCT,
			NUM_POLIZA,
			IDMODALIDAD,
			IDSUBMODALIDAD,
			NUM_FIANZA,
			NUM_EXPEDIENTE,
			NUM_AVAL_HOST,
			NUM_ANUALIDAD,
			FECHA_EMISION,
			FECHA_EFECTO,
			FECHA_VENCIMIENTO,
			IDPAIS,
			PRIMA_PROVISIONAL_INT,
			PRIMA_PROVISIONAL_EXT,
			IDDIVISA_INT,
			IDDIVISA_EXT,
			IDDIVISA_COBERTURA,
			PRIMA_MIN_INT,
			PRIMA_MIN_EXT,
			COD_MEDIADOR,
			COD_SUBCLAVE,
			P_INTERMEDIACION,
			FECHA_INICIO,
			FECHA_FIN,
			P_ESPECIAL_EMISION,
			P_ESPECIAL_RENOVACION,
			NIF_TOMADOR,
			NOMBRE_TOMADOR,
			FECHA_EFECTO_TRASPASO,
			MEDIADOR_PRINCIPAL_CIC,
			ACTIVO,
			CREATEDATE,
			MODIF_DATE,
			MODIF_USER,
			MODIF_SOURCE,
			FECHA_INICIO_OPESP,
			FECHA_FIN_OPESP
		FROM EXT.CARTERA_BKP_SMM
		WHERE (NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE) IN (SELECT NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE FROM :TEMP_CREDITO)
			AND ACTIVO = 1
		ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
		
		SELECT COUNT(*) INTO V_CONT_TOTAL_FINAL
		FROM (
			SELECT 1
			FROM EXT.CARTERA_BKP_SMM
			WHERE RAMO = :i_ramo
			AND ACTIVO = 1
			GROUP BY NUM_POLIZA,IDMODALIDAD,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE
			HAVING COUNT(*) > 1
		) X;
		
		CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'PÓLIZAS CORREGIDAS EN CRÉDITO '|| V_CONT_TOTAL - V_CONT_TOTAL_FINAL,v_proc_name,io_contador);
	END IF;
		

END IF;
CALL LIB_GLOBAL_CESCE :w_debug(i_Tenant,'FIN PROCEDIMIENTO',v_proc_name,io_contador);

END;

DO BEGIN

	DELETE FROM EXT.CSE_DEBUG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE AND PROCESO LIKE '%SP_CORREGIR%';
	SELECT * FROM EXT.CARTERA_BKP_TEST_SMM WHERE 1=1;
	-- CALL EXT.SP_CORREGIR_POLIZAS_DUPLICADAS(1,'CREDITO');
	CALL EXT.SP_CORREGIR_POLIZAS_DUPLICADAS(1,'CAUCION');
	
	SELECT * FROM EXT.CARTERA_BKP_TEST_SMM WHERE 1=1
	-- AND NUM_POLIZA = 21766
	;
	
SELECT * FROM EXT.CSE_DEBUG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE AND PROCESO LIKE '%SP_CORREGIR%';

SELECT * FROM EXT.CARTERA WHERE NUM_POLIZA = 21766 AND ACTIVO = 1 ORDER BY NUM_ANUALIDAD;
END;